### ISSUE TITLE
Failed authenticating user

### ISSUE THREAD

**Issue by ajipandean** [google-github-actions/auth#103]
### TL;DR

Unexpected result when trying to authenticate GCP service account using google-github-actions/auth@v0 module.

### Expected behavior

It should be successfully authenticated the service account

### Observed behavior

Got this error instead "google-github-actions/auth failed with: failed to parse service account key JSON credentials: unexpected token H in JSON at position 0"

### Action YAML

```yaml
name: CI/CD to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  CLOUD_RUN_REGION: asia-southeast2
  GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
  SERVICE_ACCOUNT_JSON: ${{secrets.SERVICE_ACCOUNT_JSON}}

jobs:
  main:
    name: Continous Deployment to Google Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - id: auth
        name: Authenticate service account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: $SERVICE_ACCOUNT_JSON

      - id: gcloud
        name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: $GCP_PROJECT_ID

      - id: deploy
        name: Deploy API to Google Cloud Run
        run: gcloud builds submit -f deployments/cloudbuild.staging.yaml
```

### Additional information

I just copy paste the whole generated service account keys json to Github secrets, still got the error. Any solution for this?

Thanks.

**Comment by sethvargo** [comment]
Hi @ajipandean 

Did you mean to close this issue?

**Comment by ajipandean** [comment]
Yes, I solved the problem already.

**Comment by sethvargo** [comment]
Could you please share what the problem was? It helps other users who might come across this issue. Thanks!

**Comment by ajipandean** [comment]
Yeah, sure. Just by adding a few lines of code.

```yaml
name: CI/CD to Google Cloud Run

on:
  release:
    types:
      - published

jobs:
  main:
    name: Continous Deployment to Google Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - id: auth
        name: Authenticate service account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.SERVICE_ACCOUNT_JSON}} # => here

      - id: gcloud
        name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}} # => here

      - id: deploy
        name: Deploy API to Google Cloud Run
        run: gcloud builds submit --config deployments/cloudbuild.staging.yaml

```
