### ISSUE TITLE
Optional `audience` key is invalid when unspecified

### ISSUE THREAD

**Issue by selfagency** [google-github-actions/auth#105]
### TL;DR

The docs here say `audience` is an optional key in the GitHub actions configuration. But when I run my action without the key specified, I get the following error:

![image](https://user-images.githubusercontent.com/2541728/148540261-826d3da8-54e7-43d7-9c35-96f0db87183d.png)

### Expected behavior

To run successfully without specifying an audience key.

### Observed behavior

It says the audience key is invalid.

### Action YAML

```yaml
name: Deploy - Production

on:
  workflow_dispatch:
    inputs:
      deployables:
        description: 'backend/client/dispatch.yaml'
        default: 'backend client'
        required: true
      message:
        description: 'What updates are you deploying?'
        required: true

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Disable client deploys
        if: contains(github.event.inputs.deployables, 'client')
        run: |
          # echo "::error::The client cannot be deployed at this time. See Slack for details."
          # exit 1

      - name: Disable backend deploys
        if: contains(github.event.inputs.deployables, 'backend')
        run: |
          # echo "::error::The backend cannot be deployed at this time. See Slack for details."
          # exit 1

      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0.4.1'
        with:
          workload_identity_provider:
            ${{ secrets.WORKLOAD_ID_PROVIDER_PRODUCTION }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Generate version tag
        run: |
          commit_hash=$(git rev-parse --short=7 HEAD)
          echo "version_tag=$(TZ=:UTC date +%Y-%m-%dt%H-%M-%Sutc-$commit_hash)" >> $GITHUB_ENV

      - name: Deploy
        run: |
          ${GITHUB_WORKSPACE}/deploy --production --message="${{ github.event.inputs.message }}" --actor="$GITHUB_ACTOR" --version=${{ env.version_tag }} ${{ github.event.inputs.deployables }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version_tag }}
          release_name: ${{ github.event.inputs.message }}
          draft: false
          prerelease: false
```

### Additional information

This works fine as configured in our staging environment, which is a separate Google Cloud project.

**Comment by sethvargo** [comment]
If unspecified, the audience defaults to the value of `workload_identity_provider`. Are you sure that secret is being injected into the process?

**Comment by sethvargo** [comment]
Also, what is the value for "workload_identity_provider"? It should be the full provider resource name (e.g `projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`).

**Comment by selfagency** [comment]
@sethvargo I just updated my staging config, which was working, to `projects/unstoppable-domains-staging/locations/global/workloadIdentityPools/ud-idp-gh-staging/providers/github-actions` and now it's throwing the error too.

**Comment by selfagency** [comment]
oh i see it wants the id number not the id

**Comment by sethvargo** [comment]
Hey @selfagency yea - you must use the numeric project _number_. There's an open feature request to also support the project _id_, but there's no timeline for when that feature will be released.

Does switching to the project number fix your issue?

**Comment by selfagency** [comment]
It does and doesn't. Now I can authenticate without an error, but I can't actually run any `gcloud` commands.

```yaml
      - name: Authenticate to GCP
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider:
            ${{ secrets.WORKLOAD_ID_PROVIDER_PRODUCTION }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
```

```bash
gcloud builds submit \
    --project=${project} \
    --config "${dir}/cloudbuild.yaml" \
    --substitutions=_DEPLOY_AUTH="$auth",_DEPLOY_CLIENT="$client",_DEPLOY_BACKEND_API="$backendapi",_DEPLOY_BACKEND_JOBS="$backendjobs",_DEPLOY_DISPATCH="$dispatch",_ENVIRONMENT="$environment",_SHARED_VERSION="$shared_version",_GAE_VERSION="$gae_version",_NO_PROMOTE_OPTIONS="$nopromote"
```

```bash
ERROR: (gcloud.builds.submit) There was a problem refreshing your current auth tokens: ('Unable to acquire impersonated credentials: No access token or invalid expiration in response.', '{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n')
Please run:

  $ gcloud auth login
```
