### ISSUE TITLE
Changing from `uses: google-github-actions/setup-gcloud@master` to `uses: 'google-github-actions/auth@v0'` breaks login for firebase test lab 

### ISSUE THREAD

**Issue by shonigs** [google-github-actions/auth#106]
### TL;DR

Changing from `uses: google-github-actions/setup-gcloud@master` to `uses: 'google-github-actions/auth@v0'` break firebase test lab 

In my github action I have 
```yaml
 - name: Authenticate to Google Cloud
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: '${{ secrets.GCP_SA_KEY }}'
- name: run firebase testlab
  ...
```
I get 
```
gcloud of ['gcloud', 'firebase', 'test', 'android', 'run', '--type=game-loop', ….] failed with stderr:ERROR: (gcloud.firebase.test.android.run) There was a problem refreshing your current auth tokens: ('Unable to acquire impersonated credentials: No access token or invalid expiration in response.', '{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n')
```
But old version works as expected 
```yaml
- name: Authenticate to Google Cloud
    uses: google-github-actions/setup-gcloud@master
    with:
      service_account_key: ${{ secrets.GCP_SA_KEY }}
      export_default_credentials: true
- name: run firebase testlab
...
```

Thanks

**Comment by sethvargo** [comment]
Hi @shonigs 

Can you please share the rest of your action.yml file, specifically the command(s) being run? Can you add a step to run `gcloud info` after `auth` and provide the results?

**Comment by sethvargo** [comment]
Did you _remove_ setup-gcloud from your configuration? You still need to use setup-gcloud@v0, that's what authenticates the credentials exported by auth into gcloud.

```yaml
- uses: actions/checkout@v2
- uses: google-github-actions/auth@v0
- uses: google-github-actions/setup-gcloud@v0
```
