### ISSUE TITLE
Allow ability to create workload identity token in alternative path

### ISSUE THREAD

**Issue by wimo7083** [google-github-actions/auth#109]
### TL;DR

There appears to be no way to create the token in a specific location, which makes the workflow identity something you should not use when using github actions to create PRs.

https://github.com/google-github-actions/auth/blob/main/src/main.ts#L136

### Detailed design

```markdown
name: "Generate Metadata"

on:
  workflow_dispatch: {}

jobs:
  generate-metadata
    name: Generate Metadata
    runs-on: ubuntu-20.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: main # restrict this run to only main branch, workflow_dispatch does not support limiting to a branch

      - name: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/<projectNumber>/locations/global/workloadIdentityPools/<poolname>/providers/<providerName>'
          service_account: '<serviceAccount>@<projectID>.iam.gserviceaccount.com'


      # further step to modify contents in repo

      # another step to generate token to create PR

      # another step to create PR
```

In that last step, a PR will be created with the expected changes, but the token will be included in the PR. 

In another google module, an argument is exposed to specify a different path that allows a consumer to specify where the key should be placed.

```yaml
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
          credentials_file_path: /tmp/gcp-credentials.json
```

If possible please expose a similar option.
