### ISSUE TITLE
Authenticating to docker using gcloud isn't working after this action

### ISSUE THREAD

**Issue by atrauzzi** [google-github-actions/auth#111]
### TL;DR

Authenticating to docker using gcloud isn't working, despite what looks like a successful login.

### Expected behavior

Docker to be successfully authenticated.

### Observed behavior

Docker authentication doesn't seem to be working in combination with this actions output?

### Action YAML

```yaml
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_TOKEN }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Docker Login
        run: "gcloud auth configure-docker --quiet us-central1-docker.pkg.dev"

      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: "docker build ."
```

### Log output

```text
Getting:


ERROR: (gcloud.auth.docker-helper) Failed to load credential file: [/home/runner/work/api/api/39c413352e4b4825126e788d].  File /home/runner/work/api/api/39c413352e4b4825126e788d was not found.
```

Even though:

```
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/api/api/39c413352e4b4825126e788d
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/api/api/39c413352e4b4825126e788d
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/api/api/39c413352e4b4825126e788d
```
