### ISSUE TITLE
Monorepo triggered github actions and finegrained controls

### ISSUE THREAD

**Issue by wimo7083** [google-github-actions/auth#116]
### TL;DR

We can scope workload identity for a github repo to the repo. Would it be possible to scope it to the `name` of the github action, or some other manner to isolate within a github repo?

### Detailed design

```markdown
We configure two components for github actions:
- enable workload identity for github actions in infrastructure monorepo (and give permissions).
- configure github action, in a different monorepo, that uses that service account. 

I would like platform/ infra repo to enable `service_account_a can use workload identity in `repo_a`, but only for `github_action_a`, and possibly based on other conditional triggers such as file changes or limit to a branch.

In our monorepo, without this feature it would be possible for a non-maintainer of `github_action_a` to create a new github action, that uses these permissions.
```

**Comment by wimo7083** [comment]
Again, thank you for the suggestion and link to relevant docs.

**Comment by wimo7083** [comment]
Coming back to this, and looking through related issues (now that I know what to search for). I saw this [example](https://github.com/google-github-actions/auth/issues/35#issuecomment-954100559).

I don't find it clear if I would need to include the attribute-condition:`--attribute-condition="attribute.repository_owner=username"`. What is the concern without having the `attribute-condition` when doing a custom mapping?

Would this be sufficient to ensure that the federation only works for:
- workflow: example-workflow
- repository: octo-org/octo-repo 

```bash
gcloud iam workload-identity-pools providers create-oidc "my-provider" \
  --project="${PROJECT_ID}" \
  --location="global" \
  --workload-identity-pool="my-pool" \
  --display-name="Demo provider" \
  --attribute-mapping="google.subject=assertion.sub,attribute.repository_owner=assertion.repository_owner,attribute.workflow_ref=assertion.repository:assertion.workflow" \
  --issuer-uri="https://token.actions.githubusercontent.com"

gcloud iam service-accounts add-iam-policy-binding "my-service-account@${PROJECT_ID}.iam.gserviceaccount.com" \
  --role="roles/iam.workloadIdentityUser" \
  --member="principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.workflow_ref/octo-org/octo-repo:example-workflow"
```

I suppose I don't quite understand why the attribute-condition would be needed.

**Comment by sethvargo** [comment]
It depends on your use case. In the example you provided, _any_ GitHub identity can **authenticate** to your Pool and Provider (anything signed by the public keys surfaced at token.actions.githubusercontent.com). When that authenticated principal tries to **authorize**, the IAM principal must match `octo-org/octo-repo:example-workflow`.

If you use an attribute condition, only GitHub identities that match the condition can **authenticate** to your Pool and Provider. You could then add _additional_ requirements to enable impersonation of the IAM principal, or allow the entire pool to access.

As a concrete example, you might have an attribute condition that `org == 'octo-org'` and a service account impersonation that grants some default permissions. That means any workflows in your organization can impersonate a service account that does some basic stuff. You could then have _another_ service account that's super privileged with an IAM permission tied to a specific workflow or repository. Only claims that passed the pool auth and impersonation could then use that service account.

Does that make sense?

**Comment by wimo7083** [comment]
Yes, that makes sense. By combining more or less restrictive identity pools, with more or less policy binding its possible to change the access difficulty and push the burden to either authz or authn.  You can make it easy to authenticate to a resource, but very difficult to authorize to the resource, or you can make it very difficult to authenticate to the resource with a low authorization barrier.

Thank you for explaining this further.

**Comment by wimo7083** [comment]
You've already been so helpful and instructive; I hate to ask for more, but I've hit a dead-end when I thought I was nearly there. If you could offer suggestions on how to debug principalset issues I think that is my problem.

This is how I've configured the provider, pool and principal set. 
```hcl
+ resource "google_service_account_iam_binding" "workload_identity" {
      + members            = [
          + "principalSet://iam.googleapis.com/projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/github/attribute.workflow_branch_ref/<ORG>/<REPO>/<WORKFLOW_NAME>/refs/heads/main", 
          + "principalSet://iam.googleapis.com/projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/github/attribute.workflow_ref/<ORG>/<REPO>/<WORKFLOW_NAME>",
        ]
      + role               = "roles/iam.workloadIdentityUser"
      + service_account_id = "projects/<PROJECT>/serviceAccounts/<SA_NAME>@<PROJECT>.iam.gserviceaccount.com"
    }

resource "google_iam_workload_identity_pool" "github_identity_pool" {
  provider                  = google-beta
  workload_identity_pool_id = "github"
  project                   = local.project_id
}

resource "google_iam_workload_identity_pool_provider" "github_identity_pool_provider" {
  project                            = local.project_id
  provider                           = google-beta
  workload_identity_pool_id          = google_iam_workload_identity_pool.github_identity_pool.workload_identity_pool_id
  workload_identity_pool_provider_id = "oidc-prvdr"
  attribute_mapping = {
    "google.subject"                = "assertion.sub"
    "attribute.actor"               = "assertion.actor"
    "attribute.repository"          = "assertion.repository"
    "attribute.workflow"            = "assertion.workflow"
    "attribute.ref"                 = "assertion.ref"
    "attribute.workflow_ref"        = "assertion.repository/assertion.workflow"
    "attribute.workflow_branch_ref" = "assertion.repository/assertion.workflow/assertion.ref"
  }
  oidc {
    issuer_uri = "https://token.actions.githubusercontent.com/"
  }
}
```

I've verified that SA principals were set as expected:

```bash
$ gcloud iam service-accounts get-iam-policy <SA_NAME>@<PROJEC_ID>.iam.gserviceaccount.com
bindings:
- members:
  - serviceAccount:<SA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com
  role: roles/iam.serviceAccountTokenCreator
- members:
  - principalSet://iam.googleapis.com/projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/github/attribute.workflow_branch_ref/<ORG>/<REPO>/<WORKFLOW>/refs/heads/main
  - principalSet://iam.googleapis.com/projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/github/attribute.workflow_ref/<ORG>/<REPO>/<WORKFLOW_NAME>
  role: roles/iam.workloadIdentityUser
etag: <HIDDEN>
version: 1
```

And the identity pool was created:
```bash
$ gcloud iam workload-identity-pools describe "github" --project <PROJECT> --location="global" --format="value(name)"
projects/<PROJECT_NUM>/locations/global/workloadIdentityPools/github
```

I've verified that the gitub action workflow matches the other values:

```yaml
# cat ~/.github/workflows/<WORKFLOW_NAME>.yaml
name: "<WORKFLOW_NAME"

on:
  workflow_dispatch: {}

jobs:
  <WORKFLOW_NAME>:
    name: <WORKFLOW_NAME>
    runs-on: ubuntu-20.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Post the token
        run: |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          echo $OIDC_TOKEN | base64;

      - name: 'auth'
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/<PROJECT_NUM>/locations/global/workloadIdentityPools/github/providers/oidc-prvdr'
          service_account: '<SA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com'
          create_credentials_file: true
          token_format: 'access_token' # <---- this indicates the problem is in principalset
```

Troubleshoot [docs](https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md) indicate a problem with the principalset:

> If the error message inclues "failed to generate Google Cloud access token", it means [Service Account Impersonation](https://cloud.google.com/iam/docs/workload-identity-federation#impersonation) failed. Check your Service Account Impersonation settings and ensure the principalSet is correct.

So I double-checked my attributes and found that they match the configured values in the OIDC token:

```json
{
  "repository": "<ORG>/<REPO>",
  "workflow": "<WORKFLOW_NAME>"
}
```



Currently I think the following things could be incorrect:
1. my attributes are not expanding CEL and instead using the actual values: `assertion.repository/assertion.workflow`.
```bash
    "attribute.workflow_ref"        = "assertion.repository/assertion.workflow"
    "attribute.workflow_branch_ref" = "assertion.repository/assertion.workflow/assertion.ref"
```
2. I have missed something incredibly minor somewhere I wouldn't be able to share publicly, and my replacement in this message with values like `<ORG>` would hide
3. I can only use one custom attribute at a time, but this doesn't appear to be the case from what I've seen.
