### ISSUE TITLE
An example for accessing a private repo would be handy...

### ISSUE THREAD

**Issue by donnyv12** [google-github-actions/auth#12]
First off, this is great! Very excited about getting rid of our JSON keys and migrating to this! That said, I ran into an issue when trying to get this working with private git repos, and wanted to offer to add a usage example. The main issue I ran into is that when I set permissions in the workflow, it revokes all the default permissions. I'd push a PR, but I don't have permission, but is we added this to the README it might help folks like me who are using Actions with Private Repos: 

```yaml
jobs:
  run:
    # ...

    # Add "id-token" with the intended permissions.
    # NOTE: This will revoke all default token permissions
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions
    permissions:
      contents: read
      id-token: 'write'
```
