### ISSUE TITLE
Unable to authenticate for gcloud alpha storage

### ISSUE THREAD

**Issue by louisadamian** [google-github-actions/auth#120]
### TL;DR

When trying to use gcloud alpha storage to download from a bucket after running auth with Workload Identity Federation and setup-gcloud I get an authentication error. When running the same command locally with key authentication I do not get the error.

### Expected behavior

gcloud downloads the file from my bucket

### Observed behavior

Authentication error

### Action YAML

```yaml
name: Docker Build

on:
  push:
    branches: [ main, dev/main ]
  pull_request:
    branches: [ main, dev/main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: us-central1
  REPOSITORY: aemotrics
  IMAGE: aemotrics_predict

jobs:
  docker-build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA }}
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: install deps
      run: sudo python3 -m pip install google-crc32c --target /opt/hostedtoolcache/gcloud/370.0.0/x64/lib/third_party && sudo python3 -m pip install build && gcloud --quiet auth list
    - name: Get Model
      run: gcloud --quiet alpha storage cp gs://aemotrics_models/Aemotrics_V3-Nate-2021-12-20_pruned.tar.gz ./microservice
    - name: Build Aemotrics Wheel
      run: python3 -m build -w && mkdir microservice/wheel && cp dist/* microservice/wheel/
    - name: Build the Docker image
      run: docker build microservice --tag "$IMAGE:$GITHUB_SHA"
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
```

### Log output

```text
There was a problem refreshing your current auth tokens: ('Unable to acquire impersonated credentials: No access token or invalid expiration in response.', '{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n')
```

### Additional information

when running the same command on my local machine from the same service account with key authentication I do not get the error.

**Comment by sethvargo** [comment]
How have you configured Workload Identity Federation?

**Comment by louisadamian** [comment]
yes, and it was working before it just stopped working, without changing the action yaml.

**Comment by sethvargo** [comment]
The error message makes me think something has changed with your Workload Identity Federation configuration. How is WIF configured? What are your Attribute Mappings? What are your Attribute Conditions? What principal set is configured to impersonate the Service Account?

On which step are you getting that error message?

**Comment by louisadamian** [comment]
I get the error message when I run `gcloud --quiet alpha storage cp`. My attribute mappings are attribute.actor : assertion.actor, google.subject: assertion.sub, attribute.repository : assertion.repository. I have no attribute conditions. and the principal set is configured for a service account that I know has access to the bucket I am trying to access.

**Comment by sethvargo** [comment]
What principal set is configured to impersonate the Service Account and what is the service account? You should have a service account with `Workload Identity User` permissions granted to something that looks like `principalSet://...`.

**Comment by louisadamian** [comment]
Yes it's `principalSet://iam.googleapis.com/projects/****/locations/global/workloadIdentityPools/****/attribute.repository/SurgicalPhotonics/Aemotrics`

**Comment by sethvargo** [comment]
Can you try some of the troubleshooting steps listed [here](https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md#troubleshooting)? It's generally very difficult for us to debug these kinds of issues, since we don't have access to the environment.

**Comment by louisadamian** [comment]
I changed the auth step 
```yaml
- id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA }}
        token_format: 'access_token'
```
and then I got the error `
google-github-actions/auth failed with: failed to generate Google Cloud access token for ***: {
[20](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:20)
  "error": {
[21](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:21)
    "code": 403,
[22](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:22)
    "message": "The caller does not have permission",
[23](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:23)
    "status": "PERMISSION_DENIED"
[24](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:24)
  }
[25](https://github.com/SurgicalPhotonics/aemotrics/runs/5055951311?check_suite_focus=true#step:3:25)
}
`
