### ISSUE TITLE
Generate JWT for calling Cloud Run does not seem to work

### ISSUE THREAD

**Issue by dogmatic69** [google-github-actions/auth#144]
### TL;DR

When adding `access_token_scopes` with the URL for the cloud run service the following error is displayed.

Side note: When removing `access_token_scopes` the action succeeds.

```
Error: google-github-actions/auth failed with: failed to generate Google Cloud access token for sa...@<project>.iam.gserviceaccount.com: ***
  "error": ***
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  ***
***
```

### Expected behavior

Auth token is generated that can be used to call private cloud run service

### Observed behavior

Fails due to "invalid arguments" in the request

### Action YAML

```yaml
- id: auth
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          credentials_json: ${{ secrets.credentials_json }}
          access_token_lifetime: 30s
          token_format: access_token
          access_token_scopes: ${{ inputs.endpoint }}
```
and debug info:
```
Run google-github-actions/auth@v0.6.0
  with:
    credentials_json: ***
    access_token_lifetime: 30s
    token_format: access_token
    access_token_scopes: https://<redacted>-ew.a.run.app
    create_credentials_file: true
    cleanup_credentials: true
    id_token_include_email: false
  env:
    default_branch: 
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
```
```


### Log output

_No response_

### Additional information

_No response_

**Comment by sethvargo** [comment]
Invoking a Cloud Run service requires an _id token_, not an _access access_. The `access_token_*` fields only apply to access tokens. You need to specify the audience value as `id_token_audience` and your `token_format` needs to be `"id_token"`.

```yaml
steps:
- id: 'auth'
  uses: 'google-github-actions/auth@v0'
  with:
    token_format: 'id_token'
    id_token_audience: '${{ inputs.endpoint }}'
```

There is [a more detailed example in the README](https://github.com/google-github-actions/auth#generating-an-id-token-jwt). Please let me know if you have further questions.
