### ISSUE TITLE
Error with self-hosted runner and auth

### ISSUE THREAD

**Issue by alexandre-rassinoux** [google-github-actions/auth#159]
### TL;DR

Hello,

I am currently testing Workload Identity Feature with GitHub Actions.
By launching the following workflow in a runner hosted by GitHub, everything is fine:
```
name: workflow_list_vm
on: [workflow_dispatch]
jobs:
  auth:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/projectX/locations/global/workloadIdentityPools/poolX/providers/providerX'
        service_account: 'saX@proejctX.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud compute instances list
```

However, as soon as I run the same pipeline on a self-hosted runner, it fails. I get the following error message:
```
Run google-github-actions/auth@v0
Error: google-github-actions/auth failed with: error message: Cannot read properties of undefined (reading 'message')
```

Could you help me to understand better the origin of the problem?

Thank you in advance for your help,
Sincerely,

### Action YAML

```yaml
name: workflow_list_vm
on: [workflow_dispatch]
jobs:
  auth:
    runs-on: 'self-hosted'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/projectX/locations/global/workloadIdentityPools/poolX/providers/providerX'
        service_account: 'saX@projectX.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud compute instances list
```

### Additional information

Our self-hosted runner is hosted in a GCP Compute Engine instance, behind a HTTP/HTTPS proxy without Cloud NAT, but with Private Access enabled to access Google APIs privately.
