### ISSUE TITLE
Error: $ACTIONS_ID_TOKEN_REQUEST_TOKEN is not set

### ISSUE THREAD

**Issue by hazcod** [google-github-actions/auth#16]
Hi!

Great idea, and trying to implement this for a private GitHub repository.
However, the action always errors with: `Error: $ACTIONS_ID_TOKEN_REQUEST_TOKEN is not set`.

My workflow:
```yaml
name: test
on: [pull_request]

env:
  TERRAFORM_SA: terraform@xxx

jobs:
  test:
    name: terraform
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      with:
        token_format: access_token
        access_token_lifetime: 900s
        workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/xxx
        service_account: ${{ env.TERRAFORM_SA }}
        create_credentials_file: true
        activate_credentials_file: true
    -
      name: Terraform Init
      run: terraform init
    -
      name: Terraform Validate
      run: terraform validate -no-color
    -
      name: Terraform Plan
      run: terraform plan -no-color -lock=false -input=false
    -
      name: Cleanup
      if: always()
      run: rm "${GOOGLE_APPLICATION_CREDENTIALS}" || true

```

**Comment by GregoireW** [comment]
I think you miss the id-token permission.

```
jobs:
  run:
    # Add "id-token" with the intended permissions.
    permissions:
      id-token: 'write'
      ...
```
