### ISSUE TITLE
Usage with terraform: target service indicated by the "audience" parameters is invalid

### ISSUE THREAD

**Issue by hazcod** [google-github-actions/auth#17]
Hi! Wondering how to use this with terraform (-gcs).
My workflow errors out with: 
```
Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/xxx-terraform-state/o?alt=json&delimiter=%2F&pageToken=&prefix=terraform%2Fstate%2F&prettyPrint=false&projection=full&versions=false": oauth2/google: unable to generate access token: Post "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/terraform-ci-cd@xxx.iam.gserviceaccount.com:generateAccessToken": oauth2/google: status code 400: {"error":"invalid_target","error_description":"The target service indicated by the \"audience\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist."}
```

Workflow:
```yaml
jobs:
  test:
    permissions:
      contents: read
      id-token: 'write'
    name: terraform
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      with:
        access_token_lifetime: 900s
        workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform@xxx.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true
    -
      name: Terraform Init
      run: terraform init
```

**Comment by hazcod** [comment]
I'm wondering if I would need to set `audience` to `storage.googleapis.com`.

**Comment by GregoireW** [comment]
It may be linked to an not exactly up to date  authentication library inside terraform gcloud provider (unable to understand the credentials file referring 'external' authentication provider).

Can you add a step like:

```
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file=$GOOGLE_APPLICATION_CREDENTIALS"
```
just before your terraform init step ?

**Comment by hazcod** [comment]
So trying with the following:

```yaml
jobs:
  test:
    permissions:
      contents: read
      id-token: 'write'
    name: terraform
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      uses: google-github-actions/setup-gcloud@v0.2.1
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      with:
        access_token_lifetime: 900s
        workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@xxx.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true
    -
      uses: 'google-github-actions/setup-gcloud@master'
      with:
        project_id: ${{ env.GCLOUD_PROJECT }}
    -
      name: 'gcloud login'
      run: |-
        gcloud auth login --brief --cred-file=$GOOGLE_APPLICATION_CREDENTIALS"
    -
      name: Terraform Init
      run: terraform init
```

Results in the following:

```
Successfully configured the backend "gcs"! Terraform will automatically
29
use this backend unless the backend configuration changes.
30
╷
31
│ Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/xxx-terraform-state/o?alt=json&delimiter=%2F&pageToken=&prefix=terraform%2Fstate%2F&prettyPrint=false&projection=full&versions=false": oauth2/google: unable to generate access token: Post "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/terraform@xxx.iam.gserviceaccount.com:generateAccessToken": oauth2/google: status code 400: {"error":"invalid_target","error_description":"The target service indicated by the \"audience\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist."}
```

**Comment by GregoireW** [comment]
I wonder if terraform is confused with the GOOGLE_APPLICATION_CREDENTIALS. And if you this ?  Goal is to force terraform to use the gcloud authentication, not the GOOGLE_APPLICATION_CREDENTIALS implicit one.

```yaml
jobs:
  test:
    permissions:
      contents: read
      id-token: 'write'
    name: terraform
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      uses: 'google-github-actions/setup-gcloud@master'
      with:
        project_id: ${{ env.GCLOUD_PROJECT }}
    -
      name: Authenticate to Google Cloud
      id: auth-gcloud
      uses: google-github-actions/auth@v0.3.0
      with:
        access_token_lifetime: 900s
        workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@xxx.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: false
    -
      name: 'gcloud login'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth-gcloud.outputs.credentials_file_path }}"
    -
      name: Terraform Init
      run: terraform init
...
```

**Comment by hazcod** [comment]
This results into the following error on terraform:
```
│ Error: storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by GregoireW** [comment]
Perhaps with `--update-adc` on gcloud. The step will became:

```yaml
    -
      name: 'gcloud login'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth-gcloud.outputs.credentials_file_path }}" --update-adc
```

**Comment by hazcod** [comment]
Hmm, same error.
```
│ Error: storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by GregoireW** [comment]
I did not have much idea about that, so I check the GCS backend code on terraform, and I got some weird feeling about the code here  https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/backend/remote-state/gcs/backend.go#L144

Json file management seems not great there. Perhaps you should use the access token directly like describe here: https://www.terraform.io/docs/language/settings/backends/gcs.html#access_token

You would have something like:

```yaml
jobs:
  test:
    permissions:
      contents: read
      id-token: 'write'
    name: terraform
    runs-on: ubuntu-latest
    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      name: Authenticate to Google Cloud
      id: auth-gcloud
      uses: google-github-actions/auth@v0.3.0
      with:
        token_format: access_token
        access_token_lifetime: 900s
        workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@xxx.iam.gserviceaccount.com
    -
      name: Terraform Init
      run: TF_VAR_ACCESS_TOKEN=${{ steps.auth-gcloud.outputs.access_token }} terraform init
...
```

**Comment by hazcod** [comment]
Hmm @GregoireW , now google-github-actions/auth errors out with the audience error:
```
Error: Action failed with error: Error: failed to generate Google Cloud federated token for projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github: {"error":"invalid_target","error_description":"The target service indicated by the \"audience\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist."}
```

Action:
```yaml
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      id: gcloud_auth
      with:
        token_format: access_token
        access_token_lifetime: 900s
        workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@xxx.iam.gserviceaccount.com
```

**Comment by GregoireW** [comment]
Ok then ... perhaps the error is a simple one...  

I guess you validated at least 15 times `projects/xxx/locations/global/workloadIdentityPools/main-pool/providers/github` is correct. 
Did you play a little bit enabling / disabling  the "main-pool" ?  recheck if it is really enabled.
Same with github provider. Is it really in the 'main-pool' ? is it enabled ?

**Comment by hazcod** [comment]
FWIW, seems to be correct with the exception of a weird numerical projectid.
Same when re-enabling pool and provider.

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/5222512/134921636-5f74c320-2d15-4b80-a0e5-d741a30ca038.png">

**Comment by GregoireW** [comment]
Ah! the workload identity provider is  with the project number not the project id, so it is with this wierd number:

`workload_identity_provider: 'projects/132456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'`

**Comment by hazcod** [comment]
Hmmm. :/

```
Error: Action failed with error: Error: failed to generate Google Cloud federated token for projects/132456789/locations/global/workloadIdentityPools/main-pool/providers/github: {"error":"invalid_request","error_description":"Invalid resource name supplied as 'audience': parent resource 'projects/132456789' does not exist or has been disabled/deleted."}
```

**Comment by GregoireW** [comment]
I put 123456789 because I was too lazy to put your project number: 104905...

**Comment by hazcod** [comment]
Ah wow, must be the late hour. :-)
Tried again with `1049058775616`:

```
Error: Action failed with error: Error: failed to generate Google Cloud access token for terraform-ci-cd@ironsecurity.iam.gserviceaccount.com: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

And how my iam-binding looks like:
```yaml
Updated IAM policy for serviceAccount [terraform-ci-cd@xxx.iam.gserviceaccount.com].
bindings:
- members:
  - user:me@ironpeak.be
  role: roles/iam.serviceAccountAdmin
- members:
  - principalSet://iam.googleapis.com/projects/1049058775616/locations/global/workloadIdentityPools/main-pool/attribute.repository/xxx/infrastructure
  role: roles/iam.workloadIdentityUser
etag: BwXM_YsfWbg=
version: 1
```
