### ISSUE TITLE
Strange docker login errors with absent access_token

### ISSUE THREAD

**Issue by nyanchor** [google-github-actions/auth#170]
### TL;DR

I'm trying to authenticate with gcr using the docker login command and I get no access_token output. But the auth works fine.

### Expected behavior

```bash
echo '${{ steps.auth.outputs.access_token }}'
```
should show output

### Observed behavior

```bash
echo ''
```

### Action YAML

```yaml
...
build-and-publish-new-image:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Checkout
      uses: actions/checkout@v3
    
    # GCP Setup
    - name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v0.7.1"
      with:
        create_credentials_file: true
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    
    - name: View Access token
      run: |-
        echo '${{ steps.auth.outputs.access_token }}'
    
    - name: Docker Artifacts Registry configuration
      uses: 'docker/login-action@v1'
      with:
        registry: 'gcr.io' # or REGION-docker.pkg.dev
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
```

### Log output

```text
Error: Username and password required


and 

```bash
echo ''
```
```


### Additional information

Is there something I'm missing with my yaml configs?

**Comment by sethvargo** [comment]
Hi @nyanchor 

Thank you for opening an issue. A few things:

- `create_credentials_file: true` is the default, so you don't technically need that option.

- You need to give the `auth` step an "id" property. Right now, you're referencing a step with the id "auth", but no such step exists. This should really be an error on GitHub Actions, but it silently returns the empty string instead. You need to add an "id" property to the step:

    ```yaml
    - name: "Authenticate to Google Cloud"
      id: "auth" # <--
      # ... existing values
    ```

    Then you can access the outputs. There's a more detailed example in the [Usage section of the README](https://github.com/google-github-actions/auth#usage).

- Even if you fix the output naming, it will print as `***`, because it's marked as a "secret" in GitHub Actions.

Let me know if you have any questions!
