### ISSUE TITLE
Workload Identity Federation fails when using with: token_format: 'access_token' (succeeds without it)

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [google-github-actions/auth#202]
### TL;DR

This step

```yaml
    - name: 'Authenticate to Google Cloud'
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/my-project-id/locations/global/workloadIdentityPools/my-pool/providers/gh-provider'
        service_account: 'gh-runner@my-project-id.iam.gserviceaccount.com'
```

Fails with this message:

```
Error: google-github-actions/auth failed with: retry function failed with 0 attempts: failed to generate Google Cloud federated token for projects/my-project-id/locations/global/workloadIdentityPools/my-pool/providers/gh-provider: {"error":"invalid_target","error_description":"The target service indicated by the \"audience\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist."}
```

When removing

```yaml
with:
  token_format: 'access_token'
```

it succeeds.

If I am not mistaken there are no specific [instructions](https://github.com/google-github-actions/auth#authenticating-via-service-account-key-json-1) about any extra actions needed to asκ for the specific `token_format`

### Action YAML

```yaml
name: Test workload identity federation

on:
  push:
    branches:
      - some_test_branch

jobs:
  test-authentication:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: checkout the project
      uses: 'actions/checkout@v3'

    - name: 'Authenticate to Google Cloud'
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/my-project-id/locations/global/workloadIdentityPools/my-pool/providers/gh-provider'
        service_account: 'gh-runner@my-project-id.iam.gserviceaccount.com'

    - name: use docker login action
      uses: 'docker/login-action@v1'
      with:
        registry: 'gcr.io'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: login directly via shell
      run: |-
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io
```

### Log output

```
Error: google-github-actions/auth failed with: retry function failed with 0 attempts: failed to generate Google Cloud federated token for projects/my-project-id/locations/global/workloadIdentityPools/my-pool/providers/gh-provider: {"error":"invalid_target","error_description":"The target service indicated by the \"audience\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist."}
```

### Additional information

My workload identity pool provider in `tf`

```hcl
resource "google_iam_workload_identity_pool_provider" "gh_provider" {
  provider                           = google-beta
  project                            = var.project_id
  workload_identity_pool_id          = google_iam_workload_identity_pool.my_pool.workload_identity_pool_id
  workload_identity_pool_provider_id = "gh-provider"
  attribute_mapping = {
    "google.subject" = "assertion.sub"
    "attribute.full" = "assertion.repository+assertion.ref"
  }
  oidc {
    allowed_audiences = ["https://github.com/MyOrg"]
    issuer_uri        = "https://token.actions.githubusercontent.com"
  }
}
```

**Comment by sethvargo** [comment]
Hi @pantelis-karamolegkos 

If you do not specify a token format, the action just creates the credential file. When a later step used the credential file, it would fail with the same error. The [troubleshooting steps](https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md) notes this.

If the error message includes "failed to generate Google Cloud federated token", it means admission into the Workload Identity Pool failed. Check your [Attribute Conditions](https://cloud.google.com/iam/docs/workload-identity-federation#conditions) and allowed audiences. Also, make sure you're using the project _number_ in the value for `workload_identity_provider` in the YAML, not the project _id_.

**Comment by pantelis-karamolegkos** [comment]
Thanks for your response.

So, if I get this,

> If you do not specify a token format, the action just creates the credential file. 

it will create it even if the admission failed?

**Comment by sethvargo** [comment]
Hi @pantelis-karamolegkos 

With the default parameters, the action doesn't communicate with GCP APIs _at all_. It just creates a credentials file which Application Default Credentials (ADC) use for future steps. If you request an access token or ID token, it then uses that ADC file to mint the credentials.

What is the output of:

```text
gcloud iam workload-identity-pools providers describe gh-provider --location=global --workload-identity-pool=my-pool --project=<project_id>
```

**Comment by pantelis-karamolegkos** [comment]
```
▶ gcloud iam workload-identity-pools providers describe gh-provider --location=global --workload-identity-pool=my-pool --project=my-project-id 
attributeMapping:
  attribute.full: assertion.repository+assertion.ref
  google.subject: assertion.sub
name: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/gh-provider
oidc:
  issuerUri: https://token.actions.githubusercontent.com
state: ACTIVE
```

What I see now is that I am getting

```
Error: google-github-actions/auth failed with: retry function failed with 0 attempts: failed to generate Google Cloud access token for gh-runner@my-project-id.iam.gserviceaccount.com: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

but failing to understand why the permission is denied.

I am definitely running the worklfow from `assertion.repository` repo and `assertion.ref` branch
