### ISSUE TITLE
Authenticate to artifact registry fails

### ISSUE THREAD

**Issue by steveoh** [google-github-actions/auth#206]
### TL;DR

With GCR I could authenticate but with artifact registry I cannot.  Are the scopes wrong? Are the permissions wrong on the service account? Is this supposed to work?

### Expected behavior

I expect the access token to let me in. The instructions seem to be the same.

https://cloud.google.com/artifact-registry/docs/docker/authentication#token
https://cloud.google.com/container-registry/docs/advanced-authentication#token

### Observed behavior

I am prompted for a username and password

### Action YAML

```yaml
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
- name: 🗝️ Authenticate to Google Cloud
  id: auth
  uses: google-github-actions/auth@v0
  with:
    access_token_scopes: 'email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase'
    workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
    service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
    create_credentials_file: true

- name: 🗝️ Authenticate Docker to Google Cloud works
  uses: docker/login-action@v1
  with:
    registry: gcr.io
    username: oauth2accesstoken
    password: ${{ steps.auth.outputs.access_token }}

- name: 🗝️ Authenticate Docker to Google Cloud fails
  uses: docker/login-action@v1
  with:
    registry: us-central1-docker.pkg.dev
    username: oauth2accesstoken
    password: ${{ steps.auth.outputs.access_token }}
```
