### ISSUE TITLE
gloud auth list return no account

### ISSUE THREAD

**Issue by komondor** [google-github-actions/auth#223]
### TL;DR

On version 0.8.1, authentification is successful, but gloud is not authenticated in the next step. Works on version 0.8.0 and version 0.7.3

### Expected behavior

gloud info output: 
```
 Current Properties:
     [core]
     account: [my-service-account@project-a-iam.gserviceaccount.com] (property file)
     project: [project-b] (environment)
```

### Observed behavior

gloud info output: 
```
 Current Properties:
     [core]
     account: None
     project: None
```

### Action YAML

```yaml
name: cluster-destroy
on: [workflow_dispatch]
jobs:
  cluster-destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "google auth"
        id: "auth"
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_ADMIN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - run : gcloud info
```

### Additional information

- It works fine with previous version (I tested it with 0.8.0 and 0.7.3)
- Service account root project id (project-a) differs from the project id set in the workflow (project-b)

**Comment by sethvargo** [comment]
Hi @komondor 

I am unable to reproduce this issue. With the following action.yml:

```yaml
name: 'repro'

on:
  push:
    branches:
      - 'main'

jobs:
  sake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: 'sv-actions-test'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - run: 'gcloud info'
```

gcloud is authenticated correctly:

```text
Installation Properties: [/opt/hostedtoolcache/gcloud/401.0.0/x64/properties]
User Config Directory: [/home/runner/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/home/runner/.config/gcloud/configurations/config_default]

Account: [test-sa@sv-actions-test.iam.gserviceaccount.com]
Project: [sv-actions-test]

Current Properties:
  [auth]
    credential_file_override: [/home/runner/work/ghactions-test/ghactions-test/gha-creds-6224ee7549631a8b.json] (environment)
  [core]
    account: [test-sa@sv-actions-test.iam.gserviceaccount.com] (property file)
    disable_usage_reporting: [True] (property file)
    project: [sv-actions-test] (environment)
  [metrics]
    environment: [github-actions-setup-gcloud] (environment)

Logs Directory: [/home/runner/.config/gcloud/logs]
Last Log File: [/home/runner/.config/gcloud/logs/2022.09.09/13.[45](https://github.com/sethvargo-demos/ghactions-test/runs/8271394912?check_suite_focus=true#step:5:46).42.996[58](https://github.com/sethvargo-demos/ghactions-test/runs/8271394912?check_suite_focus=true#step:5:59)3.log]
```

**Comment by mxseev** [comment]
It reproduces at my place as well.

Action:
```yaml
name: REDACTED
on:
  workflow_dispatch:

jobs:
  REDACTED:
    name: REDACTED
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Authorize to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_PROD }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - run: gcloud info
```

Output:
```
~/D/P/ ❯❯❯ act -j REDACTED -s GOOGLE_CREDENTIALS_PROD=$GOOGLE_CREDENTIALS_PROD -s PAT=$NPM_TOKEN --container-architecture linux/amd64
🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
  🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform=linux/amd64 username= forcePull=false
  🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
  🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
  🐳  docker exec cmd=[chown -R 0:0 /Users/REDACTED/Documents/Projects/REDACTED] user=0 workdir=
  ☁  git clone 'https://github.com/actions/setup-node' # ref=v2
  ☁  git clone 'https://github.com/google-github-actions/auth' # ref=v0
  ☁  git clone 'https://github.com/google-github-actions/setup-gcloud' # ref=v0
⭐ Run Main Checkout repository
  🐳  docker cp src=/Users/REDACTED/Documents/Projects/REDACTED/. dst=/Users/REDACTED/Documents/Projects/REDACTED
close /var/folders/7y/6ztkfp_j561fqfmxk2c5hscm0000gn/T/act626317871: file already closed
  🐳  docker exec cmd=[chown -R 0:0 /Users/REDACTED/Documents/Projects/REDACTED] user=0 workdir=
  ✅  Success - Main Checkout repository
⭐ Run Main Setup Node
  🐳  docker cp src=/Users/REDACTED/.cache/act/actions-setup-node@v2/ dst=/var/run/act/actions/actions-setup-node@v2/
close /var/folders/7y/6ztkfp_j561fqfmxk2c5hscm0000gn/T/act2547225108: file already closed
  🐳  docker exec cmd=[chown -R 0:0 /var/run/act/actions/actions-setup-node@v2/] user=0 workdir=
  🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-node@v2/dist/setup/index.js] user= workdir=
  💬  ::debug::isExplicit:
  💬  ::debug::explicit? false
  💬  ::debug::isExplicit: 12.22.12
  💬  ::debug::explicit? true
  💬  ::debug::isExplicit: 16.17.0
  💬  ::debug::explicit? true
  💬  ::debug::evaluating 0 versions
  💬  ::debug::match not found
| Attempting to download 14.x...
  💬  ::debug::No manifest cached
  💬  ::debug::Getting manifest from actions/node-versions@main
  💬  ::debug::check 18.9.0 satisfies 14.x
  💬  ::debug::check 18.8.0 satisfies 14.x
  💬  ::debug::check 18.7.0 satisfies 14.x
  💬  ::debug::check 18.6.0 satisfies 14.x
  💬  ::debug::check 18.5.0 satisfies 14.x
  💬  ::debug::check 18.4.0 satisfies 14.x
  💬  ::debug::check 18.3.0 satisfies 14.x
  💬  ::debug::check 18.2.0 satisfies 14.x
  💬  ::debug::check 18.1.0 satisfies 14.x
  💬  ::debug::check 18.0.0 satisfies 14.x
  💬  ::debug::check 16.17.0 satisfies 14.x
  💬  ::debug::check 16.16.0 satisfies 14.x
  💬  ::debug::check 16.15.1 satisfies 14.x
  💬  ::debug::check 16.15.0 satisfies 14.x
  💬  ::debug::check 16.14.2 satisfies 14.x
  💬  ::debug::check 16.14.1 satisfies 14.x
  💬  ::debug::check 16.14.0 satisfies 14.x
  💬  ::debug::check 16.13.2 satisfies 14.x
  💬  ::debug::check 16.13.1 satisfies 14.x
  💬  ::debug::check 16.13.0 satisfies 14.x
  💬  ::debug::check 16.12.0 satisfies 14.x
  💬  ::debug::check 16.11.1 satisfies 14.x
  💬  ::debug::check 16.11.0 satisfies 14.x
  💬  ::debug::check 16.10.0 satisfies 14.x
  💬  ::debug::check 16.9.1 satisfies 14.x
  💬  ::debug::check 16.9.0 satisfies 14.x
  💬  ::debug::check 16.8.0 satisfies 14.x
  💬  ::debug::check 16.7.0 satisfies 14.x
  💬  ::debug::check 16.6.2 satisfies 14.x
  💬  ::debug::check 16.6.1 satisfies 14.x
  💬  ::debug::check 16.6.0 satisfies 14.x
  💬  ::debug::check 16.5.0 satisfies 14.x
  💬  ::debug::check 16.4.2 satisfies 14.x
  💬  ::debug::check 16.4.1 satisfies 14.x
  💬  ::debug::check 16.4.0 satisfies 14.x
  💬  ::debug::check 16.3.0 satisfies 14.x
  💬  ::debug::check 16.2.0 satisfies 14.x
  💬  ::debug::check 16.1.0 satisfies 14.x
  💬  ::debug::check 16.0.0 satisfies 14.x
  💬  ::debug::check 14.20.0 satisfies 14.x
  💬  ::debug::x64===x64 && darwin===linux
  💬  ::debug::x64===x64 && linux===linux
  💬  ::debug::matched 14.20.0
| Acquiring 14.20.0 - x64 from https://github.com/actions/node-versions/releases/download/14.20.0-2633808318/node-14.20.0-linux-x64.tar.gz
  💬  ::debug::Downloading https://github.com/actions/node-versions/releases/download/14.20.0-2633808318/node-14.20.0-linux-x64.tar.gz
  💬  ::debug::Destination /tmp/6a3187fb-5c02-42a5-93a0-cc5dc11000f9
  💬  ::debug::download complete
| Extracting ...
  💬  ::debug::Checking tar --version
  💬  ::debug::tar (GNU tar) 1.30%0ACopyright (C) 2017 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.
| [command]/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /tmp/d9a30e0b-4d54-4c01-a4ee-f7cb7c4ddad8 -f /tmp/6a3187fb-5c02-42a5-93a0-cc5dc11000f9
| Adding to the cache ...
  💬  ::debug::Caching tool node 14.20.0 x64
  💬  ::debug::source dir: /tmp/d9a30e0b-4d54-4c01-a4ee-f7cb7c4ddad8
  💬  ::debug::destination /opt/hostedtoolcache/node/14.20.0/x64
  💬  ::debug::finished caching tool
| Done
  ❓  ##[add-matcher]/run/act/actions/actions-setup-node@v2/.github/tsc.json
  ❓  ##[add-matcher]/run/act/actions/actions-setup-node@v2/.github/eslint-stylish.json
  ❓  ##[add-matcher]/run/act/actions/actions-setup-node@v2/.github/eslint-compact.json
  ✅  Success - Main Setup Node
⭐ Run Main Authorize to Google Cloud
  🐳  docker cp src=/Users/REDACTED/.cache/act/google-github-actions-auth@v0/ dst=/var/run/act/actions/google-github-actions-auth@v0/
close /var/folders/7y/6ztkfp_j561fqfmxk2c5hscm0000gn/T/act1356152969: file already closed
  🐳  docker exec cmd=[chown -R 0:0 /var/run/act/actions/google-github-actions-auth@v0/] user=0 workdir=
  🐳  docker exec cmd=[node /var/run/act/actions/google-github-actions-auth@v0/dist/main/index.js] user= workdir=
  💬  ::debug::Using credentials JSON
  💬  ::debug::Creating credentials file
| Created credentials file at "/Users/REDACTED/Documents/Projects/REDACTED/gha-creds-e6ad813763684c62.json"
|
  ⚙  ::set-output:: credentials_file_path=/Users/REDACTED/Documents/Projects/REDACTED/gha-creds-e6ad813763684c62.json
|
  ⚙  ::set-output:: project_id=REDACTED-prod <-- correct project id from service account json
  ✅  Success - Main Authorize to Google Cloud
⭐ Run Main Set up Cloud SDK
  🐳  docker cp src=/Users/REDACTED/.cache/act/google-github-actions-setup-gcloud@v0/ dst=/var/run/act/actions/google-github-actions-setup-gcloud@v0/
close /var/folders/7y/6ztkfp_j561fqfmxk2c5hscm0000gn/T/act369210216: file already closed
  🐳  docker exec cmd=[chown -R 0:0 /var/run/act/actions/google-github-actions-setup-gcloud@v0/] user=0 workdir=
  🐳  docker exec cmd=[node /var/run/act/actions/google-github-actions-setup-gcloud@v0/dist/main/index.js] user= workdir=
  💬  ::debug::isExplicit: 401.0.0
  💬  ::debug::explicit? true
  💬  ::debug::checking cache: /opt/hostedtoolcache/gcloud/401.0.0/x64
  💬  ::debug::not found
  💬  ::debug::Downloading https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-401.0.0-linux-x86_64.tar.gz
  💬  ::debug::Destination /tmp/e2ed0932-2ee4-4b9e-86d8-ad325b0286a9
  💬  ::debug::download complete
  💬  ::debug::Checking tar --version
  💬  ::debug::tar (GNU tar) 1.30%0ACopyright (C) 2017 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.
| [command]/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /tmp/dbe0c157-39e5-44ac-80b1-0151c3571722 -f /tmp/e2ed0932-2ee4-4b9e-86d8-ad325b0286a9
  💬  ::debug::Caching tool gcloud 401.0.0 x64
  💬  ::debug::source dir: /tmp/dbe0c157-39e5-44ac-80b1-0151c3571722/google-cloud-sdk
  💬  ::debug::destination /opt/hostedtoolcache/gcloud/401.0.0/x64
  💬  ::debug::finished caching tool
| No credentials detected, skipping authentication
  ✅  Success - Main Set up Cloud SDK
⭐ Run Main gcloud info
  🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4] user= workdir=
| Google Cloud SDK [401.0.0]
|
| Platform: [Linux, x86_64] uname_result(system='Linux', node='docker-desktop', release='5.10.76-linuxkit', version='#1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021', machine='x86_64', processor='x86_64')
| Locale: ('en_US', 'UTF-8')
| Python Version: [3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]]
| Python Location: [/usr/bin/python3]
| OpenSSL: [OpenSSL 1.1.1f  31 Mar 2020]
| Requests Version: [2.22.0]
| urllib3 Version: [1.25.9]
| Site Packages: [Disabled]
|
| Installation Root: [/opt/hostedtoolcache/gcloud/401.0.0/x64]
| Installed Components:
|   bq: [2.0.75]
|   core: [2022.09.03]
|   gcloud-crc32c: [1.0.0]
|   gsutil: [5.12]
| System PATH: [/opt/hostedtoolcache/gcloud/401.0.0/x64/bin:/opt/hostedtoolcache/node/14.20.0/x64/bin:/opt/hostedtoolcache/node/16.17.0/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
| Python PATH: [/opt/hostedtoolcache/gcloud/401.0.0/x64/lib/third_party:/opt/hostedtoolcache/gcloud/401.0.0/x64/lib:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload]
| Cloud SDK on PATH: [True]
| Kubectl on PATH: [False]
|
| Installation Properties: [/opt/hostedtoolcache/gcloud/401.0.0/x64/properties]
| User Config Directory: [/root/.config/gcloud]
| Active Configuration Name: [default]
| Active Configuration Path: [/root/.config/gcloud/configurations/config_default]
|
| Account: [None]
| Project: [None]
|
| Current Properties:
|   [core]
|     disable_usage_reporting: [True] (property file)
|   [metrics]
|     environment: [github-actions-setup-gcloud] (environment)
|
| Logs Directory: [/root/.config/gcloud/logs]
| Last Log File: [None]
|
| git: [git version 2.37.3]
| ssh: [OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020]
|
|
  ✅  Success - Main gcloud info
⭐ Run Post Set up Cloud SDK
  🐳  docker exec cmd=[node /var/run/act/actions/google-github-actions-setup-gcloud@v0/dist/post/index.js] user= workdir=
| Skipping credential cleanup - "export_default_credentials" is false.
  ✅  Success - Post Set up Cloud SDK
⭐ Run Post Authorize to Google Cloud
  🐳  docker exec cmd=[node /var/run/act/actions/google-github-actions-auth@v0/dist/post/index.js] user= workdir=
| Skipping credential cleanup - $GOOGLE_GHA_CREDS_PATH is not set.
  ✅  Success - Post Authorize to Google Cloud
⭐ Run Post Setup Node
  🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-node@v2/dist/cache-save/index.js] user= workdir=
  💬  ::debug::Caching for '' is not supported
  ✅  Success - Post Setup Node
🏁  Job succeeded
```

Exactly the same action, but with version 0.8.0 (`google-github-actions/auth@v0.8.0`) works fine. Perhaps the problem is due to running Github Action locally with [act](https://github.com/nektos/act)
