### ISSUE TITLE
Looks like 0.8.3 hasn't been released.

### ISSUE THREAD

**Issue by Byeong-jun-Kim** [google-github-actions/auth#235]
### TL;DR

Looks like 0.8.2 and 0.8.3 hasn't been released.

https://github.com/marketplace/actions/authenticate-to-google-cloud

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/75416321/197755292-9c3838a3-af2b-408b-8a99-1bfce9b59626.png">

### Action YAML

```yaml
- name: Auth gcp
      uses: 'google-github-actions/auth@v0.8.1'
      with:
        workload_identity_provider: asdf
        service_account: asdf
```
