### ISSUE TITLE
v1 does not authenticate for gsutil cp

### ISSUE THREAD

**Issue by OleksiiKachan** [google-github-actions/auth#241]
### TL;DR

bumped auth and setup actions to v1
I use json service account
right after these actions I run gsutil cp
401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

works fine with v1

### Expected behavior

should run `gsutil cp` as authenticated caller

### Observed behavior

runs `gsutil cp` as anonymous caller

### Action YAML

```yaml
- name: Authenticate to gcloud
  uses: "google-github-actions/auth@v1"
  with:
    credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
- uses: 'google-github-actions/setup-gcloud@v1'
- name: Decrypt
  run: yarn decrypt --${{ env.DEPLOYMENT_ENVIRONMENT }} - this one uses gsutil cp
- name: Deploy
  uses: 'google-github-actions/deploy-appengine@v0'
  with:
    project_id: ${{ secrets.PROJECT_ID }}
    deliverables: ${{ secrets.APP_CONFIG }}
```
