### ISSUE TITLE
Unable to access GCP resources after successful Authentication through workload identity federation

### ISSUE THREAD

**Issue by mselukar008** [google-github-actions/auth#242]
Workload Identity Pool - 

```text
gcloud iam workload-identity-pools providers describe <my_provider> --location global --workload-identity-pool <my_pool_name>

attributeMapping:
  attribute.actor: assertion.actor
  attribute.repository: assertion.repository
  google.subject: assertion.sub
displayName: <my_provider>
name: projects/<my_project_id_number>/locations/global/workloadIdentityPools/<my_pool_name>/providers/<my_provider>
oidc:
  issuerUri: https://token.actions.githubusercontent.com
state: ACTIVE
```

```text
gcloud iam service-accounts get-iam-policy <my_service_account_email>

bindings:
- members:
  - serviceAccount:<my_service_account_email>
  role: roles/editor
- members:
  - principal://iam.googleapis.com/projects/<my_project_id_number>/locations/global/workloadIdentityPools/<my_pool_name>/subject/repo:github.<company>.net/<org>/<repo>
  - principalSet://iam.googleapis.com/projects/<my_project_id_number>/locations/global/workloadIdentityPools/<my_pool_name>/*
  - principalSet://iam.googleapis.com/projects/<my_project_id_number>/locations/global/workloadIdentityPools/<my_pool_name>/attribute.repository/github.<company>.net/<org>/<repo>
  role: roles/iam.workloadIdentityUser
etag: <ABCDkjg=>
version: 1
```

Workflow

```yaml
name: Resources clean up
on:  
  push:
env:
    slack_url: ${{ secrets.wh }}
jobs: 
  Clean-Up:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest    
    steps:
      - uses: 'actions/checkout@v3'        
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v1'
        with:
            create_credentials_file: 'true'
            workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/<my_pool>/providers/<my_provider>'
            service_account: 'myaccount@myproject.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'   

      - name: 'gcloud'
        run: |-
            gcloud services list
```

Issue/Error:

```text
ERROR: (gcloud.services.list) There was a problem refreshing your current auth tokens: ('Error code invalid_grant: The issuer in ID Token https://github.<company>.net/_services/token does not match the expected ones: https://token.actions.githubusercontent.com./', '{"error":"invalid_grant","error_description":"The issuer in ID Token https://github.<company>.net/_services/token does not match the expected ones: https://token.actions.githubusercontent.com./"}')
Please run:
  $ gcloud auth login
to obtain new credentials.
If you have already logged in with a different account:
    $ gcloud config set account ACCOUNT
to select an already authenticated account to use.
Error: Process completed with exit code 1.
```

![image](https://user-images.githubusercontent.com/29672753/201127265-21997791-a78a-43fe-afbb-662351db3604.png)
