### ISSUE TITLE
Auth fails with "retry function failed after 1 attempt: failed to generate Google Cloud access token"

### ISSUE THREAD

**Issue by PaulRudin** [google-github-actions/auth#243]
### TL;DR

I've tried various config, but I can't get past this error.

### Expected behavior

Successful token creation

### Observed behavior

I get the error: "retry function failed after 1 attempt: failed to generate Google Cloud access token"

### Action YAML

```yaml
name: Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.2.2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/xxx/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'xxx@yyy.iam.gserviceaccount.com'

    - name: install dependencies
      run: poetry install

    - name: Run tests
      run: poetry run pytest --mypy --cov-report=term --cov-report=xml:cov.xml --cov
      
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: cov.xml

    - name: Pytest coverage comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: cov.xml

    - name: Update Readme with Coverage Html
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\${{ steps.coverageComment.outputs.coverageHtml }}${{ steps.coverageComment.outputs.summaryReport }}<!-- Pytest Coverage Comment:End -->' ./README.md
    - name: Commit & Push changes to Readme
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: README.md
```

### Log output

```text
Run google-github-actions/auth@v1
  with:
    token_format: access_token
    workload_identity_provider: projects/xxx/locations/global/workloadIdentityPools/github-pool/providers/github-provider
    service_account: xxx@yyy.iam.gserviceaccount.com
    create_credentials_file: true
    export_environment_variables: true
    cleanup_credentials: true
    access_token_lifetime: 3600s
    access_token_scopes: https://www.googleapis.com/auth/cloud-platform
    retries: 0
    id_token_include_email: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.2/x64/lib
Created credentials file at "/home/runner/work/xxx/xxx/gha-creds-4f9276f1969ce354.json"
Error: google-github-actions/auth failed with: retry function failed after 1 attempt: failed to generate Google Cloud access token for xxx@yyy.iam.gserviceaccount.com: (403) {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

### Additional information

I've used the gh-oidc terraform module to set things up; and that applies without errors, but presumably there's some misconfiguration somewhere - but I'm not sure what I should be looking for.

https://registry.terraform.io/modules/terraform-google-modules/github-actions-runners/google/latest/submodules/gh-oidc
