### ISSUE TITLE
Action replaces GITHUB_TOKEN

### ISSUE THREAD

**Issue by quom** [google-github-actions/auth#249]
### TL;DR

Using this action (only tested using federated identity) replaces the GITHUB_TOKEN which causes downstream steps to fail which require a github identity token (e.g. updating PR labels, posting comments)

### Expected behavior

A google credentials file would be created for GCP authentication and github_token would remain the same

### Observed behavior

The github_token in the context is replaced (presumably with the google identity token?)

### Action YAML

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 20
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: ''
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_POOL }}
          service_account: ${{ secrets.GCP_CI_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Test # Requires gcp service account identity
        run: |
          pytest --junitxml=junit/test-results.xml

      - name: Publish Test Results # requires github identity
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "junit/*.xml"
```

### Log output

In the publish test results action:
```
Warning: Request GET /repos/<repository>/commits/53da57dd622f1e50d4aa0b630983f3a22c09566b/check-runs?per_page=100 failed with 403: Forbidden
```
