### ISSUE TITLE
must specify exactly one of "workload_identity_provider" or "credentials_json" error when only "credentials_json" is set

### ISSUE THREAD

**Issue by samlaycock** [google-github-actions/auth#252]
### TL;DR

I'm seeing the `must specify exactly one of "workload_identity_provider" or "credentials_json"`, but only have `credentials_json` set in the action config. I have also tried `credentials_json` and `service_account` and get the same result.

### Action YAML

```yaml
name: Example GCP Auth Login

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: GCP Login
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
```

### Log output

```text
Error: google-github-actions/auth failed with: retry function failed after 1 attempt: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.
```
