### ISSUE TITLE
Add example to TROUBLESHOOTING.md

### ISSUE THREAD

**Issue by bseib** [google-github-actions/auth#260]
### TL;DR

The following would be a good addition to your checklist of things to check when things are not working. In spite of reading the docs and following instructions, I still managed to miss adding the following to my workflow yaml file:

```
    # Add "id-token" with the intended permissions.
    # See: https://github.com/google-github-actions/auth#usage
    permissions:
      contents: 'read'
      id-token: 'write'
```

The error message for this situation begins with: "Error: google-github-actions/auth failed with: retry function failed after 1 attempt"

The first day of doing something new and getting things working is the most vulnerable time for missing tiny things, and spending hours tracking it down. This would be helpful for those people. 😄
