### ISSUE TITLE
How can I use the generated credentials file after the Actions workflows is finished?

### ISSUE THREAD

**Issue by retzero** [google-github-actions/auth#267]
### TL;DR

Hello.

I'm able to login with the generated credentials file outside of the GitHub Actions workflows during the build.
`gcloud auth login --cred-file=THE-COPIED-CREDENTIALS-JSON-FILE`

But I cannot use this anymore after the workflows is finished even if I set longer `access_token_lifetime`.
`"Can\'t issue ID_TOKEN for job in \'Completed\' state."`

Is it possible to use the generated credentials regardless of the GitHub Actions workflows status?

### Action YAML

```yaml
- id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: "access_token"
          create_credentials_file: true
          access_token_lifetime: '1800s'
          workload_identity_provider: "${{ secrets.GCPWorkloadIdentityProvider }}"
          service_account: "${{ secrets.GCPServiceAccount }}"
          id_token_audience: "${{ secrets.GCPAudience }}"

      - name: Save the credentials file for other system
        run: cp ${{ steps.auth.outputs.credentials_file_path }} /my/local/path/ # This will be used after the workflows finished!
```

### Log output

```text
ERROR: (gcloud.projects.list) There was a problem refreshing your current auth tokens: ('Unable to retrieve Identity Pool subject token', '{"$id":"1","innerException":null,"message":"Can\'t issue ID_TOKEN for job in \'Completed\' state.","typeName":"GitHub.Actions.Runtime.WebApi.CannotGenerateIdTokenException, GitHub.Actions.Runtime.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null","typeKey":"CannotGenerateIdTokenException","errorCode":0,"eventId":3000}')
```
