### ISSUE TITLE
Action failed with error: Error: $ACTIONS_ID_TOKEN_REQUEST_TOKEN is not set

### ISSUE THREAD

**Issue by hazcod** [google-github-actions/auth#27]
### TL;DR

I can't seem to get the latest version to work, although I set the permissions correctly. 🤔 

**Expected behavior**

Action working fine.

**Observed behavior**

Errors out with: `Error: Action failed with error: Error: $ACTIONS_ID_TOKEN_REQUEST_TOKEN is not set`.

### Reproduction

**Action YAML**

```yaml
name: lint
on: [pull_request]

env:
  TF_LOG: WARN

jobs:

  tflint:

    name: terraform
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps: 
    -
      uses: actions/checkout@v2
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      with:
        token_format: access_token
        access_token_lifetime: 900s
        workload_identity_provider: projects/1049058775616/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@xxx.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true
 
```

**Comment by hazcod** [comment]
Same issue for my test workflow:

```yaml
name: test
on: [pull_request]

env:
  TF_LOG: INFO
  TF_VAR_cf_email: ${{ secrets.TF_VAR_CF_EMAIL }}
  TF_VAR_cf_api_key: ${{ secrets.TF_VAR_CF_API_KEY }}
  TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
  GCLOUD_PROJECT: ironsecurity

jobs:

  test:

    name: terraform
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps: 
    -
      uses: actions/checkout@v2
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.0
      with:
        token_format: access_token
        access_token_lifetime: 900s
        workload_identity_provider: projects/1049058775616/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@xxx.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true
```

**Comment by sethvargo** [comment]
Is this a private repo or a fork? GitHub won't inject the secret from forks.

**Comment by hazcod** [comment]
This is a private GH repository.

**Comment by GregoireW** [comment]
Not sure it is related to your error, but you specify you use the last version but in your example the action is version 0.3.0 not 0.3.1. If you setup the workload identity with the process from last version and keep the 0.3.0 you should have an error like "invalid audience" not this error but ...

**Comment by hazcod** [comment]
Indeed, I get this one now:
```
{ HttpError: Invalid value for parameter 'state': "failed"
15
    at values.forEach (/node_modules/@octokit/rest/plugins/validate/validate.js:78:15)
16
    at Array.forEach (<anonymous>)
17
    at Object.keys.forEach.parameterName (/node_modules/@octokit/rest/plugins/validate/validate.js:38:12)
18
    at Array.forEach (<anonymous>)
19
    at validate (/node_modules/@octokit/rest/plugins/validate/validate.js:16:23)
20
    at process._tickCallback (internal/process/next_tick.js:68:7)
21
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
22
    at startup (internal/bootstrap/node.js:283:19)
23
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
24
  name: 'HttpError',
25
  status: 400,
26
  headers: undefined,
27
  request: undefined }
```

**Comment by sethvargo** [comment]
@hazcod is it your private repo or someone else's? GitHub has pretty strict rules and configuration about whether it will inject secrets into forks. See [this article](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository) for more information. You can learn more about [token permissions](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) in the GitHub docs too.

Also, if you're on GitHub Enterprise, I don't believe this feature has rolled out there yet.

**Comment by hazcod** [comment]
Im on the free plan, but it's odd since it used to work before. Odd!

**Comment by sethvargo** [comment]
Hi @hazcod it shouldn't matter whether you're on a paid or free plan. Can you please tell me more about your setup?

1. Is this a public or private repo?
2. Is it in a personal account or organization?
3. Is this GitHub.com or a GitHub Enterprise installation?
4. Are you submitting a Pull Request or committing directly to `main`?
    1. If you're submitting a Pull Request, are you submitting it as a branch in the same repo, or are you submitting it from a fork?

**Comment by eriksw** [comment]
I ran into this same error message but my root cause was that I forgot the `permissions:` block in my job (private repo, not a fork).

I think there's room for the error message to be more helpful, or perhaps link to a troubleshooting guide.

**Comment by hazcod** [comment]
Very odd, since this is a relatively easy Action.

```yaml
name: test
on: [pull_request]

env:
  TF_LOG: INFO
  TF_VAR_cf_email: ${{ secrets.TF_VAR_CF_EMAIL }}
  TF_VAR_cf_api_key: ${{ secrets.TF_VAR_CF_API_KEY }}
  TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
  GCLOUD_PROJECT: ironsecurity

jobs:

  test:

    name: terraform
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps: 
    -
      uses: actions/checkout@v2
    -
      uses: hashicorp/setup-terraform@v1
    -
      name: Terraform fmt
      run: terraform fmt -check=true
    -
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.1
      with:
        access_token_lifetime: 900s
        workload_identity_provider: projects/1049058775616/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: terraform-ci-cd@xxx.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true
    -
      name: Terraform Init
      run: terraform init
    -
      name: Terraform Validate
      run: terraform validate -no-color
    -
      name: Terraform Plan
      run: terraform plan -no-color -lock=false -input=false
    -
      name: Cleanup
      if: always()
      run: rm "${GOOGLE_APPLICATION_CREDENTIALS}" || true
```

This is running in a pull request opened by dependabot.

1. Private
2. Org
3. GitHub.com
4. pull request from dependabot, branch in same repo
