### ISSUE TITLE
Version 0.3.1 throws JWT errors

### ISSUE THREAD

**Issue by bogdanalecuappsbroker** [google-github-actions/auth#29]
### TL;DR
When using version 0.3.1 and performing gcloud authentication, the following error is thrown:

```bash
ERROR: gcloud crashed (OAuthError): ('Error code invalid_grant: The audience in JWT does not match the expected values.', '{"error":"invalid_grant","error_description":"The audience in JWT does not match the expected values."}')
```

**Expected behavior**
gcloud should authenticate without errors

**Observed behavior**
Using the same exact GitHub action but with version 0.3.0 no errors are thrown.

### Reproduction

**Action YAML**

```yaml
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/1234/locations/global/workloadIdentityPools/aaa/providers/bbb'
        service_account: 'sa@project.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        export GOOGLE_APPLICATION_CREDENTIALS="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth configure-docker -q
        gcloud auth list
```

**Repository**
Private repo
