### ISSUE TITLE
firebase deploy

### ISSUE THREAD

**Issue by Anasmohana84** [google-github-actions/auth#307]
### TL;DR

I'm working on a new Firebase project and I'm using GitHub action to deploy my Firebase function I got the new message Authenticating with `--token` is deprecated and will be removed in a future major version of `firebase-tools`. I have tried to use your auth to solve the problem but I can't find any document related to Firebase deployment. here is my code it works but I still use the --token arg
```
name: Deploy to Google
on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: xxx"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install libraries
      run: npm install
      working-directory: ${{env.working-directory}}
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: install firebase
      run: npm i firebase-tools -g  
    - name: deploy
      run: |-
        firebase deploy --token $(echo '${{ steps.auth.outputs.access_token }}')
```
is there any way to remove the --token
