### ISSUE TITLE
Running jobs in a private container

### ISSUE THREAD

**Issue by bgdanix** [google-github-actions/auth#309]
### TL;DR

To be able to run jobs in a container that uses a private registry for images, with Workload Identity Federation

```yml
container:
  image: europe-docker.pkg.dev/my-project/my-artifact/image:latest
  credentials:
     username: 'oauth2accesstoken'
     password: '${{ steps.auth.outputs.access_token }}'
```

### Additional information

Right now it's a chicken-egg issue as I need to first authenticate via Workload Identity Federation, but then I can't use the token in another job to pull the image from a private Artifact Registry. Just looking for guidance on what would be the best way to implement this.

**Comment by sethvargo** [comment]
Hi @bgdanix - this is a limitation of GitHub Action, and is not something we control. In this case, I believe you would need to use a longer-lived secret like a service account key and interprolate it as a GitHub Secret.

**Comment by faximan** [comment]
This is a pretty sad limitation, especially if your project/org does not allow long lived service account keys.

I'm curious if anyone else has found a (even hacky) workaround. There are some ideas floating around in https://github.com/orgs/community/discussions/38006 but none that seems to work.

**Comment by runofthemill** [comment]
@faximan I think I've come up with a viable workaround, though I have not tested it thoroughly.  The resulting `access_token` will be good for 60m, so there's some security implications as the token won't be masked in debug logs.
```
jobs:
  gcloud-setup:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.access_token.outputs.access_token}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: <project>
          workload_identity_provider: 'projects/<projectId>/locations/global/workloadIdentityPools/<pool>/providers/<provider>'
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Export Access Token
        id: access_token
        run: echo "access_token=$(gcloud auth print-access-token --impersonate-service-account <sa>@<project>.iam.gserviceaccount.com)" >> $GITHUB_OUTPUT

  job-using-private-registry-image:
    needs: gcloud-setup
    runs-on: ubuntu-latest
    container:
      image: us-central1-docker.pkg.dev/<project>/<registry>/<image>:<tag>
      credentials:
        username: oauth2accesstoken
        password: ${{ needs.gcloud-setup.outputs.access_token }}
    steps: [...]
```

**Comment by jonathonlacher** [comment]
I came across this issue from [this discussion](https://github.com/orgs/community/discussions/25225#discussioncomment-11078744);  regarding @runofthemill proposed solution.

Not sure if this is a new change, or if my token just follows a specific format, but at least on my self-hosted runners on GHES it preemptively blocks setting the token:

```
Warning: Skip output 'acr_token' since it may contain secret.
```

<img width="685" alt="Image" src="https://github.com/user-attachments/assets/b27b3b63-c650-4e6d-b330-0dd87c90d97f" />

**Comment by sorliem** [comment]
Having same issue, tried out @runofthemill 's solution and others in https://github.com/orgs/community/discussions/38006 but always results in `Error: The template is not valid. .github/workflows/example-workflow.yml (Line: 38, Col: 19): Unexpected value ''`

**Comment by Hillkorn** [comment]
Use the credentials directly in the container credentials instead.
```
container:
  image: europe-docker.pkg.dev/my-project/my-artifact/image:latest
  credentials:
    username: '_json_key'
    password: ${{ secrets.REGISTRY_JSON_CREDENTIALS }}
```
Found on https://github.com/orgs/community/discussions/38006#discussioncomment-4975385
