### ISSUE TITLE
Github actions 'Unable to acquire impersonated credentials' from GCP OIDC: error403 [principalSet mismatch with the Subject claim]

### ISSUE THREAD

**Issue by brokedba** [google-github-actions/auth#310]
### TL;DR

Hi
- I'm still struggling for a week to get my github repo to obtain a gcp access token from it's subject claim, 
-  I checked similar OIDC related errors  issues like #115 , #78 or #104 (yes there are a lot)  but nothing comes close, and doesn't exactly apply to my case.
# All I'm trying to mapp is:
the below claim
```
${MYREPO}:environment:my-env
```
- which I confirmed the structure from the official [documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token)
```
"sub": "repo:octo-org/octo-repo:environment:prod"
```
But nothing worked so far . I suspect it's due to the `principalSet` on the service account IAM binding not matching the Subject claim in the mapping-attribute of the Workload federated provider representing the github tokenID.

### Expected behavior

- the step running gcloud list services to with no error in my workflow

### Observed behavior

everything seems to be working smoothly until the part where gcloud services list command run in the next step

![image](https://github.com/google-github-actions/auth/assets/29458929/7419d5cb-2afc-4bcb-95e4-f04fa997a908)

### Action YAML

```yaml
name: 'Terraform_gcp_vpc'

on:
# ---snip-----
permissions:
  id-token: write

jobs: 
  terraform_setup:
    name: 'Terraform Init-Validate'
    runs-on: ubuntu-latest
    environment: gcp-labs
# ------ snip ------
    steps:
# Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
 #  Authenticate with GCP  using OIDC Workload Federated Identity 
    - name: 'Authenticate to Google Cloud'
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }} 
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        
  # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'   
    - id: 'gcloud'
      name: 'gcloud'
      run: gcloud services list
```

### Log output

```text
Error: (gcloud.services.list) There was a problem refreshing your current auth tokens: 'Unable to acquire impersonated credentials'
 {
  "error": {
    "code": 403,
    "message": "Permission \'iam.serviceAccounts.getAccessToken\' denied on resource (or it may not exist).",
    "status": "PERMISSION_DENIED"
    "details":
   [
      {
      "reason": "IAM_PERMISSION_DENIED",        
      "domain": "iam.googleapis.com",
      "metadata": {
      "permission": "iam.serviceAccounts.getAccessToken"
      }
    }
   ]
  }
 }

Please run:

  $ gcloud auth login
to obtain new credentials.
```

### Additional information

**Here's gist of all the steps taken to set it up including audit log if it can help**
 👉🏽: [https://bit.ly/3IIONjC](https://t.co/phHB3pg7Wv)
 
# Attribute-Mapping
![image](https://github.com/google-github-actions/auth/assets/29458929/7ab7359c-b2d6-4879-aed6-48c3f11270bd)

# PrincipalSet
```
principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.repository/${REPO}:environment:gcp-labs
```

**Comment by brokedba** [comment]
is this sub assertion correct ?:
```
"sub": "repo:org/myrepo:environment:staging"
```

**Comment by sethvargo** [comment]
> * which I confirmed the structure from the official [documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token)

Please use the [GitHub Actions OIDC debugger](https://github.com/github/actions-oidc-debugger) to verify the claims are what you expect. We've experienced situations where the documentation is incorrect.

> ## Action YAML

Can you please provide an action.yaml that uses the steps outlined in the TROUBLESHOOTING guide? Does adding `token_format: 'access_token'` cause the GitHub Action to error at the "auth" step?

```yaml
- name: 'Authenticate to Google Cloud'
  id: auth
  uses: 'google-github-actions/auth@v1'
  with:
    workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }} 
    service_account: ${{ secrets.SERVICE_ACCOUNT }}
    token_format: 'access_token' # <-- add this
```

Please also verify that the secrets are _actually_ being injected into the environment. Since neither of these values are actually "secret", I would recommend using GitHub variables instead of GitHub secrets. For the purposes of debugging, you can also hardcode them in the YAML.

---

It's really difficult to follow what you're actually trying to do here between the screenshots and abstractions with secrets and environment variables.

**Comment by brokedba** [comment]
Thank you @sethvargo for the reply . please refer to the gist for the steps I followed .
Here is  it including audit log if it can help
👉🏽: [https://bit.ly/3IIONjC](https://t.co/phHB3pg7Wv)

**Comment by sethvargo** [comment]
Can you please answer the 3 other questions? What does the OIDC debugger show as the claims? What happens when you add `token_format: 'access_token'`? Please verify that the secret is actually being injected.

**Comment by brokedba** [comment]
> Can you please answer the 3 other questions? What does the OIDC debugger show as the claims? What happens when you add `token_format: 'access_token'`? Please verify that the secret is actually being injected.

`Error: Input required and not supplied: token`  
I think I didn't adapt the template action with the  actual token .  Should I add a token from the  runner's environment instead of secret here ?
```
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: github/actions-oidc-debugger
        ref: main
        token: ${{ secrets.your-checkout-token }} <<<<
        path: ./.github/actions/actions-oidc-debugger
    - name: Debug OIDC Claims
      uses: ./.github/actions/actions-oidc-debugger
      with:
        audience: 'https://github.com/github'
```

**Comment by brokedba** [comment]
It is really really frustrating. I Knew the problem came from the Mapping attributes vs Principalset claim Patern .
But no where in the doc did GCP help developper to set the right assertions and PrincipalSet definition . WHY IS THAT ?
I had to look for youtube videos and blogs to seek for answer because  this simple subject use case `"sub": "repo:<orgName/repoName>:ref:refs/heads/branchName:environment:<environmentName>"` couldn't be explained in the documentation . 
I lost 2 weeks in this .
- Now I added attribute.repository= assertion_repository and a second principalset and it works although that's not exactly what I want but clearly demonstrate that developers are left to guess if they want to add anything like  `branch` and `environment` to their claim subject.

**Comment by sethvargo** [comment]
Hi @brokedba - awesome. I'm glad you were able to figure it out!

**Comment by brokedba** [comment]
My OP's issue is  I can't get this to be recognized using following claim :
```
"sub": "repo:<orgName/repoName>:environment:<environmentName>" 
```
I'm not satisfied with the answer yet as repository attribute I used is too broad .
I then tried the below concatenation which didn't work [403 error]:
```
1. provider 

gcloud iam workload-identity-pools providers create-oidc "gitaction-oidc-provider" --project="${PROJECT_ID}" \
--location="global" --workload-identity-pool="github-pool" --display-name="gitactions-oidc-provider" \
 --attribute-mapping="google.subject=assertion.sub,attribute.full=assertion.repository+assertion.environment \
  --issuer-uri="https://token.actions.githubusercontent.com/"

2. Principalset

gcloud iam service-accounts add-iam-policy-binding "$SA" \
--project="${PROJECT_ID}" --role="roles/iam.workloadIdentityUser" \
--member="principalSet://[iam.googleapis.com](http://iam.googleapis.com/)/${WORKLOAD_IDENTITY_POOL_ID}/attribute.full/${REPO}:environment:gcp-labs" 
```

**Comment by sethvargo** [comment]
Here is what I meant by trying to reproduce the issue with the smallest number of steps:

```yaml
name: 'repro'

on:
  push:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  job:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'github/actions-oidc-debugger@main'
        with:
          audience: 'https://iam.googleapis.com/projects/99343382058/locations/global/workloadIdentityPools/github/providers/github'

      - id: 'auth'
        uses: 'google-github-actions/auth@main'
        with:
          workload_identity_provider: 'projects/99343382058/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'external@poopy-candles.iam.gserviceaccount.com'
          token_format: 'access_token'
```

This will print out the OIDC token claims and attempt to generate a token. As I expected, the value for `sub` does not always match what is [in GitHub's documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token). GitHub's documentation says the value for `sub` is `repo:octo-org/octo-repo:environment:prod`, but when I used the [GitHub Actions OIDC debugger](https://github.com/github/actions-oidc-debugger), the result was `repo:sethvargo-demos/ghactions-test:ref:refs/heads/main`. The `sub` can undertake [many different values and formats](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-subject-claims), so the first thing to check is to make sure that the subject is the value that you're expecting. Note, this is how GitHub works and has nothing to do with Google Cloud.

I was able to get this working fine. Here's my pool configuration:

<img width="965" alt="provider-config" src="https://github.com/google-github-actions/auth/assets/408570/9ee6c809-d5d4-403a-8e0a-e94554bee825">

And here's the Service Account permission which has `Workload Identity User` permissions.

```text
principal://iam.googleapis.com/projects/99343382058/locations/global/workloadIdentityPools/github/subject/repo:sethvargo-demos/ghactions-test:ref:refs/heads/main
```
