### ISSUE TITLE
Error in parsing JSON credentials file

### ISSUE THREAD

**Issue by rojo1997** [google-github-actions/auth#315]
### TL;DR

Error in parsing JSON credentials file. The yaml workflow file and the credential have not been modified. It is failing since today June 22nd. Yesterday it was working properly.

### Expected behavior

Correct credentials setup

### Observed behavior

It is repeatedly trying to parse a JSON credential file that works locally.

### Action YAML

```yaml
- name: Authenticate to Google Cloud
        id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ env.GCP_KEY_JSON }}"
```

### Log output

```text
Error: google-github-actions/auth failed with: retry function failed after 4 attempts: failed to parse service account key JSON credentials: unexpected token \ in JSON at position 1
```

### Additional information

We are using the variable from env since we loaded it with Vault. We have verified that the content of the variable is correct (name of the file with the credentials).
