### ISSUE TITLE
How to authenticate for IAP

### ISSUE THREAD

**Issue by mbrevda** [google-github-actions/auth#327]
(how) can this action be used to generate a token that can be used for programmatic access to IAP?  I've tried a million combinations of settings but can't end up with a valid bearer token. 

<details>
<summary>snippet of one of the things I tried</summary>

```js
const getAuth = async () => {
  const auth = new GoogleAuth();
  const client = await auth.getIdTokenClient(targetAudience);
  const {headers} = await client.getRequestMetadataAsync();
  return headers;
};
```

</details>

but this errors with `throw new Error('Cannot fetch ID token in this environment, use GCE or set the GOOGLE_APPLICATION_CREDENTIALS environment variable to a service account credentials JSON file.');`

Are there any examples that can be followed?

**Comment by mbrevda** [comment]
To answer my own question:

```
with:
          workload_identity_provider: ...
          service_account: ...
          token_format: 'id_token'
          id_token_audience: ....apps.googleusercontent.com
          id_token_include_email: true
```

and use `${{ steps.gcloud_auth.outputs.id_token }}` to access the token
