### ISSUE TITLE
Authenticate multiple projects in a single github action job

### ISSUE THREAD

**Issue by dheerajmav** [google-github-actions/auth#330]
I have multiple projects (dev, QA, prod) how do i authenticate to all projects in a single job?

action.yml - 
```
pull-gcr-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - id: 'auth-qa'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_QA }}
          service_account: ${{ secrets.GH_SERVICE_ACCOUNT_QA }}
      - id: 'auth-prod'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GH_SERVICE_ACCOUNT_PROD }} 
```
Issue - 
<img width="704" alt="image" src="https://github.com/google-github-actions/auth/assets/112712368/fcd6d6f3-0ae9-4bd8-b0f4-edc8c9cfe186">

Error -
`denied: Permission for QA gcr, since it got replaced by prod creds`

Note - It works with a single service account shared between projects, but we can't share service account in this case.
