### ISSUE TITLE
There was a problem refreshing your current auth tokens: ('Error code invalid_target: The target service indicated by the "audience" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn\'t exist.'

### ISSUE THREAD

**Issue by RedHoes** [google-github-actions/auth#333]
### TL;DR

I set up the code to allows GitHub Actions workflows to access resources in Google Cloud Platform (GCP)
I add a Google Cloud Workload Identity Provider using Terraform.

### Action YAML

```yaml
id: 'gcloud'
name: 'Gcloud'
run: |-
    gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
    gcloud services list
```

### Log output

```text
ERROR: (gcloud.config.set) There was a problem refreshing your current auth tokens: ('Error code invalid_target: The target service indicated by the "audience" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn\'t exist.', '{"error":"invalid_target","error_description":"The target service indicated by the \\"audience\\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn\'t exist."}')
```
