### ISSUE TITLE
v2 Breaking Change

### ISSUE THREAD

**Issue by JoleneSF** [google-github-actions/auth#360]
### TL;DR

This action fails now after working a few days ago. The error tells to upgrade to `v2`, and no documentation indicates changes required. However, the upgrade breaks the action workflow.

### Expected behavior

Two possible options are expected for me:
1. The auth works as before.
2. The documentation, changelog, or release notes indicate what needs to be done to fix the breaking change.

### Observed behavior

The original action YAML:

```yml
name: Build and Plan Development

on:
  push:
    branches: [ trunk ]

jobs:
  build_push_dev:
    name: Build Dev
    needs: [ identify ]
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci
    - name: Authenticate with Google Cloud
      id: auth_dev
      uses: google-github-actions/auth@v0
      with:
        token_format: access_token
        workload_identity_provider: projects/12345/locations/global/workloadIdentityPools/github-actions/providers/github-actions
        service_account: ABCDEFG@foo.iam.gserviceaccount.com
        access_token_lifetime: 300s
```

Results in the following output:

```sh
# Run google-github-actions/auth@v0
  with:
    token_format: access_token
    workload_identity_provider: projects/12345/locations/global/workloadIdentityPools/github-actions/providers/github-actions
    service_account: ABCDEFG@foo.iam.gserviceaccount.com
    access_token_lifetime: 300s
    create_credentials_file: true
    export_environment_variables: true
    cleanup_credentials: true
    access_token_scopes: https://www.googleapis.com/auth/cloud-platform
    retries: 0
    id_token_include_email: false
Error: The v0 series of google-github-actions/auth is no longer maintained. It will not receive updates, improvements, or security patches. Please upgrade to the latest supported versions: 

    https://github.com/google-github-actions/auth
Created credentials file at "/home/runner/work/tideswell/tideswell/gha-creds-b2edbfb028811c8f.json"
Error: google-github-actions/auth failed with: retry function failed after 1 attempt: failed to generate Google Cloud access token for ABCDEFG@foo.iam.gserviceaccount.com: (403) {
  "error": {
    "code": 403,
    "message": "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "IAM_PERMISSION_DENIED",
        "domain": "iam.googleapis.com",
        "metadata": {
          "permission": "iam.serviceAccounts.getAccessToken"
        }
      }
    ]
  }
}
```

The upgraded action with `google-github-actions/auth@v2` is shown below, along with the new (current) log output.

### Action YAML

```yaml
name: Build and Plan Development

on:
  push:
    branches: [ trunk ]

jobs:
  build_push_dev:
    name: Build Dev
    needs: [ identify ]
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci
    - name: Authenticate with Google Cloud
      id: auth_dev
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: projects/12345/locations/global/workloadIdentityPools/github-actions/providers/github-actions
        service_account: ABCDEFG@foo.iam.gserviceaccount.com
        access_token_lifetime: 300s
```

### Log output

```text
Error: google-github-actions/auth failed with: retry function failed after 4 attempts: failed to generate Google Cloud OAuth 2.0 Access Token for ABCDEFG@foo.iam.gserviceaccount.com: {
  "error": {
    "code": 403,
    "message": "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "IAM_PERMISSION_DENIED",
        "domain": "iam.googleapis.com",
        "metadata": {
          "permission": "iam.serviceAccounts.getAccessToken"
        }
      }
    ]
  }
}
```
