### ISSUE TITLE
Save application default credentials (ADC)

### ISSUE THREAD

**Issue by mering** [google-github-actions/auth#383]
### TL;DR

Save ADC at `${HOME}/.config/gcloud/application_default_credentials.json` instead of workspace.

### Detailed design

Instead of saving the credentials file in the workspace which is prone to be overwritten for example by the checkout action, save it to the well-known location at `${HOME}/.config/gcloud/application_default_credentials.json`.

We currently use the following step (which also deals with multi-line secrets correctly):
```yaml
- name: Create service account credentials files
  env:
    ROBOT_JSON_KEY: ${{ secrets.ROBOT_JSON_KEY }}
  run: |
    mkdir -p "${HOME}/.config/gcloud"
    echo "${ROBOT_JSON_KEY}" > "${HOME}/.config/gcloud/application_default_credentials.json"
    gcloud auth activate-service-account --key-file "${HOME}/.config/gcloud/application_default_credentials.json"
```

We use it mainly with Bazel RBE via `bazel --google_default_credentials=true`.

It would be nice if we could replace this step by using `google-github-actions/auth` action instead.
