### ISSUE TITLE
"create_credentials_file" option

### ISSUE THREAD

**Issue by that70schris** [google-github-actions/auth#395]
https://github.com/google-github-actions/auth/blob/51342a1a91dfd798639e5ce9c0c4fde05bb24f6a/src/main.ts#L171

I'm a bit confused by this warning: 
```
The "create_credentials_file" option is true, but the current GitHub workspace is empty. Did you forget to use "actions/checkout" before this step? If you do not intend to share authentication with future steps in this job, set "create_credentials_file" to false.
```

is a bit confusing.  In my case I do need the credentials file for `get-gke-credentials`, but have no need to checkout the code.
example:
```
name: Rollout

env:
  IMAGE: us-docker.pkg.dev/${{ vars.GCP_PROJECT }}/main/${{ inputs.image }}
  TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

on:
  workflow_call:
    inputs:
      image:
        description: Name of image to use
        required: true
        type: string
      resource:
        description: Name of the cloud resource
        required: true
        type: string
      type:
        description: Kubernetes resource type
        default: deployment
        type: string
      target:
        description: Dockerfile target
        type: string

jobs:
  rollout:
    name: Rollout ${{ inputs.image }} to ${{ inputs.resource }}
    environment: ${{ github.ref_type == 'tag' && 'production' || github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP }}

      - name: GKE auth
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: main
          location: us-central1

      - name: Rollout
        run: kubectl set image ${{ inputs.type }} ${{ inputs.resource }}
          main=${{ env.IMAGE }}:${{ env.TAG }}
          ${{ inputs.target == 'run-subscriber' && 'dead-letter-subscriber=$IMAGE:$TAG' || '' }}

      - name: Check Rollout Status
        if: ${{ inputs.type == 'deployment' }}
        run: kubectl rollout status deployment ${{ inputs.resource }}
```
