### ISSUE TITLE
Post Clean Up Issue

### ISSUE THREAD

**Issue by juliusoh** [google-github-actions/auth#411]
### TL;DR

Error: google-github-actions/auth post failed with: failed to remove "/home/runner/work/*/gha-creds-7d2206b70566553e.json": EACCES: permission denied, unlink '/home/runner/work/*/gha-creds-7d2206b70566553e.json'

### Action YAML

```yaml
permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: stage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
```

**Comment by sethvargo** [comment]
Are you using self-hosted runners? Does this happen all the time? Please provide the full debug logs.

**Comment by juliusoh** [comment]
> Are you using self-hosted runners? Does this happen all the time? Please provide the full debug logs.

These are GitHub hosted runners and happens all the time

**Comment by sethvargo** [comment]
Could you please provide the full debug logs? There are instructions in the Troubleshooting steps above. Please also provide your complete action.yml.

**Comment by jacek-jablonski** [comment]
Same problem here. I sent the debug logs by email as instructed.

**Comment by lucianxquatium** [comment]
Same here. It started to fail 4 days ago. Followed the [troubleshooting guide](https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md) but nothing helped. 

We are also using a GH-hosted runner, not the latest one, and it happens all the time.
For authentication we use WIP with a SA. 

```yml
  job-name:
    runs-on: ubuntu-20.04
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/....../providers/githubwif'
          service_account: '......iam.gserviceaccount.com'
```
