### ISSUE TITLE
Google Maps (routing) not playing nicely with WIF

### ISSUE THREAD

**Issue by emigre459** [google-github-actions/auth#459]
### TL;DR

When using other GCP services (e.g. BigQuery, CloudStorage, etc.), I can use WIF with no service account in GH runners without issue. Trying to do the same approach with Google Maps Routing v2 keeps failing with a scoping error I cannot resolve.

### Expected behavior

The error mentioned in the TLDR; is:

```bash
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: ('Error code invalid_request: Scope(s) must be provided.', '{"error":"invalid_request","error_description":"Scope(s) must be provided."}')
``` 

I have not been able to find any maps-specific scopes that make sense nor have I been able to find Maps roles to add to my WIF pool to enable usage with that API as described in #454 (even adding mapsadmin.admin role did not solve anything). Is it possible that WIF (without a service account at least) does not play nicely with GMaps APIs currently and an API key approach is the only solve for now?

### Action YAML

```yaml
name: package_testing
on:
    push:
        branches:
            - main
    pull_request:

env:
    GMAPS_API_KEY: ${{ secrets.GMAPS_API_KEY }}
    GCP_ORG_ID: ${{ secrets.GCP_ORG_ID }}
    GCP_REGION: ${{ vars.GCP_REGION }}
    NREL_API_KEY: ${{ secrets.NREL_API_KEY }}
    ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
    PROXY_URI_REQUESTS: ${{ secrets.PROXY_URI_REQUESTS }}

jobs:
    fail_fast_maps:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout actions
              uses: actions/checkout@v4
            - id: gcp_auth
              name: GCP authentication
              uses: google-github-actions/auth@v2
              with:
                project_id: ${{ vars.GCP_PROJECT_ID }}
                workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/my-repo

            - id: 'gcloud'
              name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
            - name: 'Use gcloud CLI'
              run: 'gcloud info'
            - name: Setup python
              id: setup-python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ vars.PYTHON_VERSION }}
            - name: Install poetry
              run: |
                curl -sSL https://install.python-poetry.org | python3 -
            - name: Make the environment
              run: make env_create
            - name: Run tests
              run: poetry run pytest -n auto -v tests/test_maps.py
```

### Log output

```text
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: ('Error code invalid_request: Scope(s) must be provided.', '{"error":"invalid_request","error_description":"Scope(s) must be provided."}')
```
