### ISSUE TITLE
Gcloud 507 and above starts reporting bq warning

### ISSUE THREAD

**Issue by jprecuch** [google-github-actions/auth#464]
### TL;DR

When auth done through this action I can see warning being reported after gcloud 507 was released. Was working fine on 506 and below.
```
      - name: Login to Google for GKE/BQ
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          workload_identity_provider: ${{ secrets.MOONSTONE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.MOONSTONE_SERVICE_ACCOUNT }}
```
ends with
```
WARNING: `--scopes` flag may not working as expected and will be ignored for account type external_account.
```
Output:
```
bq show --format=prettyjson moonstone_dataset
+ DATASET_LOCATION='WARNING: `--scopes` flag may not working as expected and will be ignored for account type external_account.
{
  "access": [
    {
      "role": "WRITER",
      "specialGroup": "projectWriters"
    },
    {
      "role": "OWNER",
      "specialGroup": "projectOwners"
    },
    {
      "role": "OWNER",
      "userByEmail": "REDACTED"
    },
    {
      "role": "READER",
      "specialGroup": "projectReaders"
    }
  ],
  "creationTime": "1709[56](URL#step:13:57)0942416",
  "datasetReference": {
    "datasetId": "moonstone_dataset",
```

### Expected behavior

No warning should be printed?

### Action YAML

```yaml
- name: Login to Google for GKE/BQ
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          workload_identity_provider: ${{ secrets.MOONSTONE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.MOONSTONE_SERVICE_ACCOUNT }}
```

### Log output

```text

```
