### ISSUE TITLE
How to output token and pass to other action when using Direct WIF

### ISSUE THREAD

**Issue by mike-pt** [google-github-actions/auth#470]
Docs are a bit lacking into how to do this with Direct WIF but I bumped into to this sample from: https://github.com/docker/login-action/issues/640#issuecomment-2440150987

```
      # Setup Google Cloud SDK
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      # Authenticate to Google Artifact Registry (GAR)
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: 'us-docker.pkg.dev'
```

I get no errors in the 1st setup but then login-action fails with , missing password, so I tried to debug the possible different outputs and all seems to be null:

 ------------------------
steps.auth.outputs.access_token: 
steps.auth.outputs.id_token: 
steps.auth.outputs.auth_token: 
steps.auth.outputs.credentials_file_path: 

What am I missing?
