### ISSUE TITLE
I am getting The GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json" Error !

### ISSUE THREAD

**Issue by mihir-mehta** [google-github-actions/auth#52]
### TL;DR

Even though there is only crdentials i am using for workflow. I am getting following error 

The GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"!

### Expected behavior

The workflow should work as per my understanding 

### Action YAML

```yaml
name: Build and Deploy to Cloud Run

# Defining Triggers.
# In our case : any push to the dev_omipar branch
on:
  push:
    branches:
    - dev_omipar

# Defining ENV vars internal to the flow
env:
  PROJECT_ID: datalake-298101
  REGION: us-central1
  DEPLOYMENT_NAME: omipar-dev
  IMAGE: omipar-dev

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:

    # Checking out code from github repo
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test > coverage.txt
      env:
        CI: true
    - uses: papeloto/action-zip@v1
      with:
        files: coverage/ index.json
        dest: result.zip

    # Setup gcloud SDK access to cloud resources by refering to github Secrets store
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.gcp_credentials }}
        project_id: ${{ env.PROJECT_ID }}


    # Configure Docker to use the gcloud command-line tool as a helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    
    # upload
    - name: 'Upload assets to GCP bucket, CDN'
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.gcp_credentials }}
    - uses: google-github-actions/upload-cloud-storage@v0.4.0
      with:
        path: coverage
        destination: omipar-release-test-case-reports
    
    # Build the Docker image
    - name: Build
      run: |-
        sudo docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:latest" .
    # Push the updated build into the GCR registry
    - uses: mattes/gce-docker-push-action@v1
      with:
        creds: ${{ secrets.gcp_credentials }}
        src: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE}}:latest
        dst: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE}}:latest
        
    # - name: Send mail
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     # Required mail server address:
    #     server_address: smtp.gmail.com
    #     # Required mail server port:
    #     server_port: 465
    #     # Optional (recommended): mail server username:
    #     username: ${{secrets.USERNAME}}
    #     # Optional (recommended) mail server password:
    #     password: ${{secrets.PASSWORD}}
    #     # Required mail subject:
    #     subject: Github Actions job result
    #     # Required recipients' addresses:
    #     to: mihirpmehta@gmail.com
    #     # Required sender full name (address can be skipped):
    #     from: Mihir Mehta # <mihirpmehta@gmail.com>
    #     # Optional whether this connection use TLS (default is true if server_port is 465)
    #     secure: true
    #     # Optional plain body:
    #     body: Build job of ${{github.repository}} completed successfully!
    #     # Optional HTML body read from file:
    #     # html_body: file://result.zip
    #     attachments: result.zip
    #     # Optional unsigned/invalid certificates allowance:
    #     ignore_cert: true
    #     # Optional converting Markdown to HTML (set content_type to text/html too):
    #     convert_markdown: true
    - name: Send email through SendGrid
      uses: peter-evans/sendgrid-action@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: ${{env.DEPLOYMENT_NAME}}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE}}:latest
        project_id: ${{ env.PROJECT_ID }}
        region: ${{env.REGION}}
        credentials: ${{ secrets.gcp_credentials }}
        flags: --service-account gcr-write-access@datalake-298101.iam.gserviceaccount.com --memory 2Gi
```
