### ISSUE TITLE
Generate access_token from json credentials?

### ISSUE THREAD

**Issue by jacek-jablonski** [google-github-actions/auth#58]
Hi,

Is it possible to generate `access_token` from `credentials_json`?

Here is what I am trying to do:
```yaml
# ...
jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
         id: gcp-auth
         uses: google-github-actions/auth@v0.4.0
         with:
           credentials_json: ${{ secrets.gcp-sa-key }}
           token_format: 'access_token'
           access_token_lifetime: '300s'
```

but I am getting:

```
Error: Action failed with error: Error: Failed to generate Google Cloud access token for ***
  "error": ***
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  ***
***
```

Additional information: above account has role `Service Account Token Creator`.

Thanks.
