### ISSUE TITLE
[Help] Am I supposed to set ACTIONS_ID_TOKEN_REQUEST_URL

### ISSUE THREAD

**Issue by peavers** [google-github-actions/auth#62]
Hey sorry this is probably a dumb question but I've read through the readme, and I've copied pasted each setup step exactly without issue. However when I try and authenticate I get 

```
Error: Action failed with error: Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```

Am I supposed to set `ACTIONS_ID_TOKEN_REQUEST_URL` as a Action Secret, if so where do I get this value on the GCP console? 

I'm just trying a really basic example using:
```
      - id: 'auth'
        name: Login to Google Storage
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'my-provider'
          service_account: ' my-service-account@my-project.iam.gserviceaccount.com'

      - name: Upload to Google Storage
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: ${{steps.download.outputs.download-path}}/*
          destination: my-bucket/release
```
